export type LocalizedText = { es: string; en: string };

export const EDITORIAL_CATEGORIES = [
  { id: "preguntas-respuestas", name: { es: "Preguntas y respuestas filosóficas", en: "Philosophical questions and answers" }, description: { es: "Preguntas cotidianas examinadas sin respuestas prefabricadas.", en: "Everyday questions examined without ready-made answers." } },
  { id: "filosofia", name: { es: "Filosofía", en: "Philosophy" }, description: { es: "Tradiciones, problemas y modos de leer el mundo.", en: "Traditions, problems and ways of reading the world." } },
  { id: "conceptos", name: { es: "Conceptos", en: "Concepts" }, description: { es: "Ideas fundamentales explicadas con precisión y contexto.", en: "Fundamental ideas explained with precision and context." } },
  { id: "claridad", name: { es: "Claridad del pensamiento", en: "Clarity of thought" }, description: { es: "Instrumentos para distinguir preguntas, supuestos y tensiones.", en: "Tools for distinguishing questions, assumptions and tensions." } },
  { id: "podcast", name: { es: "Podcast", en: "Podcast" }, description: { es: "Lecturas para escuchar y seguir pensando.", en: "Readings to listen to and keep thinking with." } },
  { id: "ensayos", name: { es: "Ensayos", en: "Essays" }, description: { es: "Argumentos largos sobre la vida contemporánea.", en: "Long-form arguments about contemporary life." } },
  { id: "investigaciones", name: { es: "Investigaciones", en: "Research" }, description: { es: "Mapas documentados de problemas, obras y genealogías.", en: "Documented maps of problems, works and genealogies." } },
  { id: "perspectivas", name: { es: "Perspectivas y movimientos", en: "Perspectives and movements" }, description: { es: "Pensadores y corrientes puestos en relación.", en: "Thinkers and traditions placed in relation." } },
] as const;

export type EditorialCategoryId = (typeof EDITORIAL_CATEGORIES)[number]["id"];

type Seed = {
  category: EditorialCategoryId;
  slug: string;
  title: LocalizedText;
  dek: LocalizedText;
  thesis: LocalizedText;
  tension: LocalizedText;
  practice: LocalizedText;
  references?: LocalizedText[];
};

const S: Seed[] = [
  { category:"preguntas-respuestas", slug:"que-significa-vivir-bien", title:{es:"¿Qué significa vivir bien?",en:"What does it mean to live well?"}, dek:{es:"Una pregunta antigua que no se resuelve acumulando bienestar.",en:"An ancient question that accumulating comfort cannot settle."}, thesis:{es:"Vivir bien no designa un estado de satisfacción permanente, sino una forma coherente de ordenar acciones, vínculos y fines.",en:"Living well is not permanent satisfaction but a coherent way of ordering actions, relationships and ends."}, tension:{es:"Aristóteles subraya el florecimiento mediante hábitos; los estoicos, la libertad interior ante lo que no controlamos. Ambas vías preguntan qué merece gobernar una vida.",en:"Aristotle stresses flourishing through habits; the Stoics, inner freedom before what we cannot control. Both ask what deserves to govern a life."}, practice:{es:"Observa una semana y distingue placer, reconocimiento y sentido. ¿Qué actividades seguirían importándote aunque nadie las viera?",en:"Observe one week and distinguish pleasure, recognition and meaning. Which activities would still matter if nobody saw them?"} },
  { category:"preguntas-respuestas", slug:"somos-realmente-libres", title:{es:"¿Somos realmente libres?",en:"Are we really free?"}, dek:{es:"Entre condicionamiento, hábito y capacidad de responder.",en:"Between conditioning, habit and our capacity to respond."}, thesis:{es:"La libertad rara vez es ausencia de límites. Aparece como la capacidad de reconocer condicionamientos y responder sin obedecerlos de manera automática.",en:"Freedom is rarely the absence of limits. It appears as the capacity to recognize conditions and respond without automatically obeying them."}, tension:{es:"Spinoza asocia libertad con comprender las causas; Sartre insiste en que incluso no elegir es una elección. Uno reduce la ilusión, el otro radicaliza la responsabilidad.",en:"Spinoza links freedom to understanding causes; Sartre insists that even not choosing is a choice. One reduces illusion, the other radicalizes responsibility."}, practice:{es:"Nombra una conducta que llamas elección. Separa deseo, presión, hábito y margen real de acción antes de juzgarte libre o determinado.",en:"Name one behavior you call a choice. Separate desire, pressure, habit and real room for action before judging yourself free or determined."} },
  { category:"preguntas-respuestas", slug:"por-que-tememos-cambiar", title:{es:"¿Por qué tememos cambiar?",en:"Why do we fear change?"}, dek:{es:"El temor protege algo, incluso cuando inmoviliza.",en:"Fear protects something, even when it immobilizes us."}, thesis:{es:"El miedo al cambio no siempre es cobardía: a menudo protege continuidad, pertenencia o una identidad que todavía no sabemos reemplazar.",en:"Fear of change is not always cowardice: it often protects continuity, belonging or an identity we do not yet know how to replace."}, tension:{es:"Kierkegaard ve angustia en la apertura de lo posible; Burke recuerda que lo heredado contiene saber tácito. Cambiar exige distinguir prudencia de evasión.",en:"Kierkegaard sees anxiety in the openness of possibility; Burke reminds us inherited practices contain tacit knowledge. Change requires distinguishing prudence from avoidance."}, practice:{es:"En vez de preguntar si debes cambiar, pregunta qué pérdida imaginas y qué evidencia necesitarías para avanzar un paso reversible.",en:"Instead of asking whether you should change, ask what loss you imagine and what evidence would justify one reversible step."} },
  { category:"preguntas-respuestas", slug:"que-le-debemos-a-los-demas", title:{es:"¿Qué les debemos a los demás?",en:"What do we owe one another?"}, dek:{es:"De la obligación abstracta al encuentro concreto.",en:"From abstract obligation to concrete encounter."}, thesis:{es:"La obligación hacia otros nace tanto de principios compartibles como de la vulnerabilidad concreta que aparece ante nosotros.",en:"Obligation to others arises both from shareable principles and from the concrete vulnerability before us."}, tension:{es:"Kant exige reglas universalizables; Levinas sitúa la responsabilidad antes de cualquier contrato. La justicia necesita norma, pero también atención.",en:"Kant demands universalizable rules; Levinas places responsibility before any contract. Justice needs rules, but also attention."}, practice:{es:"Ante un conflicto, formula una regla que aceptarías para cualquiera y luego pregunta qué detalle singular esa regla podría estar ignorando.",en:"In a conflict, formulate a rule you would accept for anyone, then ask what singular detail that rule might ignore."} },
  { category:"preguntas-respuestas", slug:"puede-el-sufrimiento-tener-sentido", title:{es:"¿Puede el sufrimiento tener sentido?",en:"Can suffering have meaning?"}, dek:{es:"Dar sentido no equivale a justificar el daño.",en:"Making meaning does not mean justifying harm."}, thesis:{es:"El sufrimiento no es valioso por sí mismo. El sentido, cuando aparece, proviene de la respuesta, el vínculo o la transformación que construimos frente a él.",en:"Suffering is not valuable in itself. Meaning, when it appears, comes from the response, relationship or transformation we build around it."}, tension:{es:"Nietzsche pregunta qué puede transformarse; Camus rechaza consolaciones falsas. Ambos impiden romantizar el dolor, aunque abren respuestas distintas.",en:"Nietzsche asks what can be transformed; Camus rejects false consolation. Both resist romanticizing pain while opening different responses."}, practice:{es:"No preguntes primero para qué ocurrió. Pregunta qué necesita cuidado ahora y qué relato no traiciona la realidad de lo vivido.",en:"Do not first ask what it happened for. Ask what needs care now and what story does not betray the reality of what was lived."} },

  { category:"filosofia", slug:"para-que-sirve-la-filosofia", title:{es:"¿Para qué sirve la filosofía?",en:"What is philosophy for?"}, dek:{es:"No entrega recetas: mejora la calidad de las preguntas.",en:"It gives no recipes: it improves the quality of questions."}, thesis:{es:"La filosofía sirve para hacer visibles los conceptos con los que interpretamos una situación y las consecuencias de sostenerlos.",en:"Philosophy makes visible the concepts through which we interpret a situation and the consequences of holding them."}, tension:{es:"Puede buscar verdad, orientar la vida o criticar estructuras. Reducirla a bienestar personal pierde su dimensión pública; reducirla a teoría pierde su fuerza práctica.",en:"It can seek truth, orient life or criticize structures. Reducing it to wellbeing loses its public dimension; reducing it to theory loses its practical force."}, practice:{es:"Toma una palabra que uses con seguridad —éxito, libertad, justicia— y pregunta qué incluye, qué excluye y quién gana con esa definición.",en:"Take a word you use confidently—success, freedom, justice—and ask what it includes, excludes and who benefits from that definition."} },
  { category:"filosofia", slug:"el-arte-de-preguntar", title:{es:"El arte de preguntar",en:"The art of asking"}, dek:{es:"Una buena pregunta cambia el campo de lo posible.",en:"A good question changes the field of possibility."}, thesis:{es:"Preguntar filosóficamente no es pedir información, sino examinar el marco que hace que ciertas respuestas parezcan obvias.",en:"To ask philosophically is not to request information but to examine the frame that makes certain answers seem obvious."}, tension:{es:"Sócrates desarma certezas mediante diálogo; Gadamer entiende la pregunta como apertura a algo que puede transformarnos.",en:"Socrates dismantles certainty through dialogue; Gadamer understands the question as openness to something that can transform us."}, practice:{es:"Convierte una pregunta binaria en tres: qué estás protegiendo, qué estás suponiendo y qué evidencia cambiaría tu lectura.",en:"Turn a binary question into three: what are you protecting, what are you assuming and what evidence would change your reading?"} },
  { category:"filosofia", slug:"filosofia-y-vida-cotidiana", title:{es:"Filosofía y vida cotidiana",en:"Philosophy and everyday life"}, dek:{es:"Pensar comienza antes de los libros y continúa después de ellos.",en:"Thinking begins before books and continues after them."}, thesis:{es:"Toda vida cotidiana contiene ideas sobre tiempo, deber, éxito y relación. La filosofía vuelve examinables esas ideas tácitas.",en:"Everyday life contains ideas about time, duty, success and relationship. Philosophy makes those tacit ideas examinable."}, tension:{es:"La reflexión puede alejarnos de la acción o volverla más lúcida. La diferencia está en si el concepto regresa a la experiencia y acepta ser corregido por ella.",en:"Reflection can distance us from action or make it clearer. The difference lies in whether the concept returns to experience and accepts correction by it."}, practice:{es:"Elige una rutina automática y escribe la idea de vida buena que parece expresar. Después decide si todavía la reconoces como propia.",en:"Choose an automatic routine and write the idea of a good life it seems to express. Then decide whether you still recognize it as yours."} },
  { category:"filosofia", slug:"leer-un-filosofo-sin-obedecerlo", title:{es:"Leer a un filósofo sin obedecerlo",en:"Reading a philosopher without obeying"}, dek:{es:"Una perspectiva es un instrumento, no una autoridad final.",en:"A perspective is an instrument, not a final authority."}, thesis:{es:"Leer bien implica reconstruir el argumento en su mejor versión y conservar el derecho a discutir sus límites.",en:"Good reading means reconstructing an argument in its strongest form while retaining the right to dispute its limits."}, tension:{es:"La admiración favorece comprensión; la distancia favorece crítica. Sin la primera caricaturizamos, sin la segunda convertimos pensamiento en doctrina.",en:"Admiration favors understanding; distance favors criticism. Without the first we caricature; without the second we turn thought into doctrine."}, practice:{es:"Formula primero qué problema resolvía el autor. Solo después pregunta qué deja fuera y qué ha cambiado desde su contexto.",en:"First state what problem the author was solving. Only then ask what is left out and what has changed since their context."} },
  { category:"filosofia", slug:"pensar-en-tiempos-de-urgencia", title:{es:"Pensar en tiempos de urgencia",en:"Thinking in urgent times"}, dek:{es:"La rapidez puede resolver tareas y empobrecer juicios.",en:"Speed can solve tasks and impoverish judgment."}, thesis:{es:"Pensar despacio no significa posponer indefinidamente, sino proteger un intervalo donde hechos, valores y consecuencias no se confundan.",en:"Thinking slowly does not mean postponing forever but protecting an interval where facts, values and consequences are not confused."}, tension:{es:"La acción exige oportunidad; el juicio exige pausa. Una práctica madura sabe qué necesita respuesta inmediata y qué merece demora.",en:"Action requires timing; judgment requires pause. A mature practice knows what needs an immediate response and what deserves delay."}, practice:{es:"Antes de responder algo importante, escribe por separado: lo que sabes, lo que interpretas, lo que temes y lo que aún falta preguntar.",en:"Before an important response, write separately what you know, interpret, fear and still need to ask."} },

  { category:"conceptos", slug:"libertad", title:{es:"Libertad",en:"Freedom"}, dek:{es:"No solo elegir, sino comprender desde dónde elegimos.",en:"Not only choosing, but understanding where choice begins."}, thesis:{es:"Libertad puede significar ausencia de interferencia, capacidad efectiva, autonomía racional o creación de sí. Cada definición ilumina y oculta algo.",en:"Freedom can mean non-interference, effective capability, rational autonomy or self-creation. Each definition reveals and conceals something."}, tension:{es:"La libertad individual puede chocar con condiciones sociales que vuelven algunas opciones meramente formales.",en:"Individual freedom can collide with social conditions that make some options merely formal."}, practice:{es:"Cuando digas “soy libre de hacerlo”, añade dos preguntas: ¿puedo realmente? y ¿qué fuerzas están moldeando mi deseo?",en:"When you say “I am free to do it,” add two questions: can I really, and what forces are shaping my desire?"} },
  { category:"conceptos", slug:"justicia", title:{es:"Justicia",en:"Justice"}, dek:{es:"Dar a cada cual lo suyo exige discutir qué cuenta como suyo.",en:"Giving each their due requires asking what counts as due."}, thesis:{es:"La justicia ordena instituciones y relaciones mediante criterios de igualdad, mérito, necesidad, libertad o reparación.",en:"Justice orders institutions and relationships through criteria of equality, merit, need, freedom or repair."}, tension:{es:"Tratar igual puede perpetuar desigualdades previas; tratar distinto puede parecer arbitrario. La discusión depende del criterio y de la historia.",en:"Equal treatment can perpetuate prior inequality; different treatment can seem arbitrary. The dispute depends on criterion and history."}, practice:{es:"Ante una distribución, identifica qué criterio se usa, quién lo definió y qué desigualdad previa permanece invisible.",en:"In any distribution, identify the criterion used, who defined it and which prior inequality remains invisible."} },
  { category:"conceptos", slug:"autenticidad", title:{es:"Autenticidad",en:"Authenticity"}, dek:{es:"Ser uno mismo no significa ignorar que somos con otros.",en:"Being oneself does not mean ignoring that we exist with others."}, thesis:{es:"La autenticidad no consiste en expresar cualquier impulso, sino en apropiarse de una vida que siempre comienza en lenguajes y vínculos heredados.",en:"Authenticity is not expressing every impulse but taking ownership of a life that always begins within inherited languages and relationships."}, tension:{es:"Heidegger contrapone apropiación y anonimato; Beauvoir recuerda que la libertad propia se realiza junto a otras libertades.",en:"Heidegger contrasts ownership and anonymity; Beauvoir reminds us our freedom is realized alongside other freedoms."}, practice:{es:"Distingue entre lo que deseas, lo que esperas que otros reconozcan y aquello con lo que estarías dispuesto a comprometerte.",en:"Distinguish what you desire, what you want others to recognize and what you are willing to commit to."} },
  { category:"conceptos", slug:"responsabilidad", title:{es:"Responsabilidad",en:"Responsibility"}, dek:{es:"Responder por los actos y ante quienes afectan.",en:"Answering for actions and to those they affect."}, thesis:{es:"Responsabilidad reúne autoría, previsión y capacidad de reparación. No depende solo de intención: también atiende consecuencias y relaciones.",en:"Responsibility joins authorship, foresight and capacity for repair. It depends not only on intention but also consequences and relationships."}, tension:{es:"Exigir responsabilidad sin reconocer límites puede ser cruel; invocar condicionamientos para borrar toda agencia vuelve imposible la vida común.",en:"Demanding responsibility without recognizing limits can be cruel; invoking conditions to erase all agency makes common life impossible."}, practice:{es:"Describe qué controlabas, qué podías prever, quién fue afectado y qué reparación sigue siendo posible.",en:"Describe what you controlled, what you could foresee, who was affected and what repair remains possible."} },
  { category:"conceptos", slug:"sentido", title:{es:"Sentido",en:"Meaning"}, dek:{es:"Orientación, inteligibilidad y valor no son exactamente lo mismo.",en:"Direction, intelligibility and value are not exactly the same."}, thesis:{es:"El sentido puede ser una dirección elegida, una narración que vuelve inteligible la experiencia o un valor que merece sostenerse.",en:"Meaning can be a chosen direction, a narrative that makes experience intelligible or a value worth sustaining."}, tension:{es:"Buscar un significado total puede inmovilizar; vivir sin orientación puede fragmentar. El sentido también puede ser local, revisable y compartido.",en:"Seeking total meaning can paralyze; living without direction can fragment. Meaning may also be local, revisable and shared."}, practice:{es:"Pregunta qué vuelve valioso este día concreto, no qué justifica toda tu existencia de una vez.",en:"Ask what makes this particular day worthwhile, not what justifies your entire existence at once."} },

  { category:"claridad", slug:"separar-hechos-interpretaciones", title:{es:"Separar hechos de interpretaciones",en:"Separating facts from interpretations"}, dek:{es:"Una distinción sencilla que cambia conversaciones difíciles.",en:"A simple distinction that changes difficult conversations."}, thesis:{es:"Los hechos describen observaciones comprobables; las interpretaciones organizan su significado. Confundirlos convierte una lectura en certeza.",en:"Facts describe verifiable observations; interpretations organize their meaning. Confusing them turns a reading into certainty."}, tension:{es:"No existe mirada completamente neutra, pero eso no vuelve equivalentes todas las interpretaciones. Algunas explican mejor y requieren menos supuestos.",en:"There is no completely neutral view, but that does not make all interpretations equal. Some explain better and require fewer assumptions."}, practice:{es:"Divide una hoja en “observé” e “interpreté”. Reescribe cada frase hasta que otra persona pueda reconocer la diferencia.",en:"Divide a page into “I observed” and “I interpreted.” Rewrite each sentence until another person could recognize the difference."} },
  { category:"claridad", slug:"detectar-supuestos", title:{es:"Cómo detectar un supuesto",en:"How to detect an assumption"}, dek:{es:"Lo que no se dice suele organizar todo lo demás.",en:"What goes unsaid often organizes everything else."}, thesis:{es:"Un supuesto es una premisa que opera sin ser examinada. Puede ser razonable, pero su invisibilidad le concede poder excesivo.",en:"An assumption is a premise operating without examination. It may be reasonable, but invisibility gives it excessive power."}, tension:{es:"No podemos pensar sin supuestos; tampoco debemos tratarlos como hechos. La claridad consiste en volverlos revisables.",en:"We cannot think without assumptions; nor should we treat them as facts. Clarity means making them revisable."}, practice:{es:"Completa la frase “esto solo tiene sentido si es verdad que…”. Después busca una excepción y observa qué cambia.",en:"Complete the sentence “this only makes sense if it is true that…”. Then seek an exception and notice what changes."} },
  { category:"claridad", slug:"nombrar-la-tension", title:{es:"Nombrar la tensión",en:"Naming the tension"}, dek:{es:"Muchos problemas persisten porque contienen dos bienes incompatibles.",en:"Many problems persist because they contain two incompatible goods."}, thesis:{es:"Una tensión no es necesariamente un error que deba eliminarse. Puede ser el conflicto legítimo entre valores que importan a la vez.",en:"A tension is not necessarily an error to eliminate. It may be a legitimate conflict between values that matter simultaneously."}, tension:{es:"Libertad y pertenencia, cuidado y verdad, estabilidad y crecimiento no siempre admiten síntesis perfecta.",en:"Freedom and belonging, care and truth, stability and growth do not always admit a perfect synthesis."}, practice:{es:"Escribe la situación como “quiero cuidar X sin traicionar Y”. Esa fórmula evita que un valor monopolice el análisis.",en:"Write the situation as “I want to protect X without betraying Y.” This prevents one value from monopolizing the analysis."} },
  { category:"claridad", slug:"reformular-una-pregunta", title:{es:"Reformular una pregunta",en:"Reframing a question"}, dek:{es:"Cambiar el marco puede abrir opciones antes invisibles.",en:"Changing the frame can reveal previously invisible options."}, thesis:{es:"Reformular no maquilla un problema: modifica la unidad de análisis para examinar causas, valores o posibilidades que la pregunta original cerraba.",en:"Reframing does not disguise a problem: it changes the unit of analysis to examine causes, values or possibilities the original question closed off."}, tension:{es:"Una reformulación puede liberar o evadir. Es útil cuando conserva el costo real de la situación y amplía la comprensión.",en:"A reframe can liberate or evade. It is useful when it preserves the real cost of the situation while widening understanding."}, practice:{es:"Transforma “¿A o B?” en “¿qué necesidad intento atender con A y con B, y qué tercera forma existe?”.",en:"Turn “A or B?” into “what need am I trying to meet with A and B, and what third form exists?”"} },
  { category:"claridad", slug:"pensar-sin-delegar-el-juicio", title:{es:"Pensar sin delegar el juicio",en:"Thinking without outsourcing judgment"}, dek:{es:"Una herramienta puede ampliar tu mirada sin ocupar tu lugar.",en:"A tool can widen your view without taking your place."}, thesis:{es:"La ayuda intelectual es valiosa cuando hace visibles alternativas y razones, no cuando sustituye la responsabilidad de juzgar.",en:"Intellectual assistance is valuable when it makes alternatives and reasons visible, not when it replaces the responsibility to judge."}, tension:{es:"Buscamos claridad precisamente cuando dudamos, y esa vulnerabilidad vuelve tentadora una respuesta autoritaria.",en:"We seek clarity precisely when uncertain, and that vulnerability makes an authoritative answer tempting."}, practice:{es:"Después de recibir una recomendación, escribe qué parte reconoces como propia, qué rechazas y qué información aún necesitas.",en:"After receiving a recommendation, write which part you recognize as yours, what you reject and what information you still need."} },

  { category:"podcast", slug:"escuchar-a-dostoievski", title:{es:"Escuchar a Dostoievski: libertad y culpa",en:"Listening to Dostoevsky: freedom and guilt"}, dek:{es:"Una puerta sonora a Los hermanos Karamázov.",en:"An audio doorway into The Brothers Karamazov."}, thesis:{es:"Dostoievski dramatiza una libertad que desea absolverse de toda autoridad y descubre que la inocencia también puede convertirse en evasión.",en:"Dostoevsky dramatizes a freedom that wants release from all authority and discovers that innocence can also become evasion."}, tension:{es:"Si todo está permitido, la responsabilidad no desaparece: se vuelve más difícil de atribuir y soportar.",en:"If everything is permitted, responsibility does not disappear: it becomes harder to assign and bear."}, practice:{es:"Escucha el episodio y anota qué personaje enuncia una idea que tú rechazas pero comprendes mejor después de oírla.",en:"Listen to the episode and note which character voices an idea you reject but understand better afterward."} },
  { category:"podcast", slug:"kafka-y-la-culpa-sin-causa", title:{es:"Kafka y la culpa sin causa",en:"Kafka and guilt without cause"}, dek:{es:"El proceso como experiencia de una norma ilegible.",en:"The Trial as the experience of an unreadable norm."}, thesis:{es:"Kafka muestra cómo una institución puede producir obediencia incluso cuando nadie logra explicar la acusación.",en:"Kafka shows how an institution can produce obedience even when nobody can explain the accusation."}, tension:{es:"Necesitamos reglas para convivir, pero una regla que no puede ser interrogada convierte responsabilidad en sometimiento.",en:"We need rules to live together, but a rule that cannot be questioned turns responsibility into submission."}, practice:{es:"Escucha dónde el protagonista empieza a colaborar con el marco que lo acusa. ¿Qué alternativa deja de imaginar?",en:"Listen for where the protagonist begins collaborating with the frame accusing him. What alternative does he stop imagining?"} },
  { category:"podcast", slug:"hesse-y-la-identidad-dividida", title:{es:"Hesse y la identidad dividida",en:"Hesse and the divided self"}, dek:{es:"El lobo estepario más allá del individuo contra el mundo.",en:"Steppenwolf beyond the individual against the world."}, thesis:{es:"La novela cuestiona la fantasía de un yo único y descubre una pluralidad de voces, edades y deseos.",en:"The novel questions the fantasy of a single self and discovers a plurality of voices, ages and desires."}, tension:{es:"La unidad ofrece continuidad; la multiplicidad ofrece movimiento. Convertir una identidad provisional en esencia puede volverla prisión.",en:"Unity offers continuity; multiplicity offers movement. Turning a provisional identity into an essence can make it a prison."}, practice:{es:"Mientras escuchas, identifica dos versiones de ti que sueles presentar como incompatibles y pregunta qué situación convoca a cada una.",en:"While listening, identify two versions of yourself you usually treat as incompatible and ask which situation calls each one forth."} },
  { category:"podcast", slug:"orwell-lenguaje-y-poder", title:{es:"Orwell: lenguaje y poder",en:"Orwell: language and power"}, dek:{es:"Cuando reducir palabras reduce también lo pensable.",en:"When reducing words also reduces what can be thought."}, thesis:{es:"El poder no solo prohíbe discursos: puede estrechar el vocabulario con el que una sociedad reconoce su experiencia.",en:"Power does not only prohibit speech: it can narrow the vocabulary through which a society recognizes experience."}, tension:{es:"Un lenguaje común permite coordinación, pero su simplificación puede borrar diferencias necesarias para criticar.",en:"A shared language enables coordination, but its simplification can erase distinctions needed for criticism."}, practice:{es:"Elige una palabra pública muy repetida y pregunta qué experiencias distintas comprime bajo una sola etiqueta.",en:"Choose a frequently repeated public word and ask which different experiences it compresses under one label."} },
  { category:"podcast", slug:"camus-y-la-rebelion-lucida", title:{es:"Camus y la rebelión lúcida",en:"Camus and lucid revolt"}, dek:{es:"Vivir sin una garantía final de sentido.",en:"Living without a final guarantee of meaning."}, thesis:{es:"Camus no propone resignación ante el absurdo, sino una fidelidad a la experiencia que rehúsa tanto el consuelo falso como la destrucción.",en:"Camus proposes not resignation before the absurd but fidelity to experience that refuses both false consolation and destruction."}, tension:{es:"Aceptar que no hay garantía puede liberar o vaciar. La rebelión camusiana intenta sostener límites y solidaridad.",en:"Accepting there is no guarantee can liberate or empty life. Camusian revolt tries to sustain limits and solidarity."}, practice:{es:"Escucha buscando la diferencia entre esperanza, ilusión y compromiso con lo que sí está presente.",en:"Listen for the difference between hope, illusion and commitment to what is actually present."} },

  { category:"ensayos", slug:"la-fatiga-de-tener-una-opinion", title:{es:"La fatiga de tener una opinión",en:"The fatigue of having an opinion"}, dek:{es:"Por qué la exposición constante no equivale a juicio.",en:"Why constant exposure does not amount to judgment."}, thesis:{es:"La cultura de reacción inmediata confunde presencia pública con pensamiento y vuelve sospechosa cualquier pausa.",en:"The culture of immediate reaction confuses public presence with thought and makes every pause seem suspicious."}, tension:{es:"Callar puede proteger la reflexión o abandonar una responsabilidad pública. El criterio no es velocidad, sino calidad de atención y consecuencias.",en:"Silence can protect reflection or abandon a public responsibility. The criterion is not speed but quality of attention and consequences."}, practice:{es:"Antes de opinar, formula la mejor versión de dos posiciones y declara qué dato podría hacerte revisar la tuya.",en:"Before giving an opinion, formulate the strongest version of two positions and state what evidence could make you revise yours."} },
  { category:"ensayos", slug:"la-intimidad-en-la-era-del-perfil", title:{es:"La intimidad en la era del perfil",en:"Intimacy in the age of the profile"}, dek:{es:"Ser legible para una plataforma no es ser conocido.",en:"Being legible to a platform is not being known."}, thesis:{es:"El perfil convierte una vida en atributos comparables; la intimidad conserva ambigüedad, contexto y derecho a cambiar.",en:"The profile turns a life into comparable attributes; intimacy preserves ambiguity, context and the right to change."}, tension:{es:"La personalización puede servirnos, pero también fijarnos en patrones pasados y volver rentable nuestra previsibilidad.",en:"Personalization can serve us, but it can also fix us in past patterns and make our predictability profitable."}, practice:{es:"Revisa qué sistemas describen quién eres y pregunta qué puedes corregir, borrar o impedir que vuelva a usarse.",en:"Review which systems describe who you are and ask what you can correct, delete or prevent from being used again."} },
  { category:"ensayos", slug:"contra-la-claridad-falsa", title:{es:"Contra la claridad falsa",en:"Against false clarity"}, dek:{es:"Una respuesta nítida también puede deformar el problema.",en:"A crisp answer can also distort the problem."}, thesis:{es:"La claridad genuina no elimina toda ambigüedad: distingue qué está resuelto, qué permanece abierto y por qué.",en:"Genuine clarity does not eliminate all ambiguity: it distinguishes what is settled, what remains open and why."}, tension:{es:"Necesitamos conclusiones para actuar, pero una conclusión prematura puede ocultar conflictos de valor que volverán después.",en:"We need conclusions to act, but a premature conclusion can hide value conflicts that return later."}, practice:{es:"Termina un análisis con tres columnas: lo claro, lo incierto y lo que no puede saberse todavía.",en:"End an analysis with three columns: what is clear, uncertain and cannot yet be known."} },
  { category:"ensayos", slug:"memoria-que-no-se-vuelve-destino", title:{es:"Una memoria que no se vuelve destino",en:"A memory that does not become destiny"}, dek:{es:"Recordar patrones sin encerrar a la persona en ellos.",en:"Remembering patterns without trapping a person inside them."}, thesis:{es:"Una memoria útil devuelve continuidad a la reflexión, pero debe permanecer editable, contextual y subordinada al presente.",en:"Useful memory gives continuity to reflection, but must remain editable, contextual and subordinate to the present."}, tension:{es:"Sin memoria repetimos; con una memoria rígida somos interpretados por una versión antigua de nosotros mismos.",en:"Without memory we repeat; with rigid memory we are interpreted by an old version of ourselves."}, practice:{es:"Conserva solo recuerdos que puedas leer y discutir. Añade fecha y contexto para evitar que una observación se convierta en identidad.",en:"Keep only memories you can read and dispute. Add date and context so an observation does not become an identity."} },
  { category:"ensayos", slug:"el-derecho-a-cambiar-de-idea", title:{es:"El derecho a cambiar de idea",en:"The right to change your mind"}, dek:{es:"La coherencia no exige permanecer idénticos.",en:"Consistency does not require remaining identical."}, thesis:{es:"Cambiar de idea puede expresar inconstancia, pero también fidelidad a mejores razones o a una experiencia nueva.",en:"Changing one's mind can express inconsistency, but also fidelity to better reasons or new experience."}, tension:{es:"La vida pública premia posiciones estables; el pensamiento vivo necesita admitir corrección sin borrar responsabilidad por lo anterior.",en:"Public life rewards stable positions; living thought must admit correction without erasing responsibility for what came before."}, practice:{es:"Explica un cambio con tres elementos: qué creías, qué encontraste y qué responsabilidad conserva tu posición anterior.",en:"Explain a change with three elements: what you believed, what you encountered and what responsibility your former position retains."} },

  { category:"investigaciones", slug:"genealogia-del-trabajo-como-identidad", title:{es:"Genealogía del trabajo como identidad",en:"A genealogy of work as identity"}, dek:{es:"Cómo una actividad económica llegó a responder quiénes somos.",en:"How an economic activity came to answer who we are."}, thesis:{es:"La identificación moderna entre profesión e identidad combina vocación religiosa, disciplina industrial y cultura del rendimiento.",en:"The modern identification of profession and identity combines religious vocation, industrial discipline and performance culture."}, tension:{es:"El trabajo puede ofrecer reconocimiento y mundo común, pero también absorber formas de valor que no producen rendimiento medible.",en:"Work can offer recognition and a common world, but also absorb forms of value that produce no measurable performance."}, practice:{es:"Investiga qué partes de tu presentación personal dependen del trabajo y qué quedaría si esa ocupación cambiara.",en:"Investigate which parts of your self-presentation depend on work and what would remain if that occupation changed."}, references:[{es:"Max Weber, La ética protestante y el espíritu del capitalismo.",en:"Max Weber, The Protestant Ethic and the Spirit of Capitalism."},{es:"Hannah Arendt, La condición humana.",en:"Hannah Arendt, The Human Condition."}] },
  { category:"investigaciones", slug:"historia-de-la-atencion", title:{es:"Breve historia filosófica de la atención",en:"A brief philosophical history of attention"}, dek:{es:"De ejercicio del alma a recurso disputado.",en:"From exercise of the soul to contested resource."}, thesis:{es:"La atención ha sido entendida como disciplina, oración, percepción activa y, hoy, recurso económico capturable.",en:"Attention has been understood as discipline, prayer, active perception and, today, an economic resource to capture."}, tension:{es:"No toda distracción es fracaso individual: los entornos diseñan hábitos. Pero reconocer la estructura no elimina la práctica personal.",en:"Not every distraction is individual failure: environments design habits. But recognizing structure does not eliminate personal practice."}, practice:{es:"Registra durante un día quién solicita tu atención, qué ofrece a cambio y qué proyecto propio queda interrumpido.",en:"For one day record who requests your attention, what they offer in return and which project of your own gets interrupted."}, references:[{es:"Simone Weil, La atención y la voluntad.",en:"Simone Weil, Attention and Will."},{es:"William James, Principios de psicología.",en:"William James, Principles of Psychology."}] },
  { category:"investigaciones", slug:"mapa-de-la-libertad", title:{es:"Siete sentidos de la libertad",en:"Seven meanings of freedom"}, dek:{es:"Un mapa comparado para no discutir con una sola palabra.",en:"A comparative map for avoiding arguments over one word."}, thesis:{es:"Libertad negativa, positiva, republicana, existencial, racional, material y espiritual responden a problemas diferentes.",en:"Negative, positive, republican, existential, rational, material and spiritual freedom answer different problems."}, tension:{es:"Debates aparentemente insolubles suelen usar la misma palabra para criterios incompatibles.",en:"Apparently insoluble debates often use the same word for incompatible criteria."}, practice:{es:"Cuando aparezca “libertad”, pregunta: ¿libre de qué, capaz de qué, junto a quién y bajo qué condiciones?",en:"When “freedom” appears, ask: free from what, capable of what, alongside whom and under what conditions?"}, references:[{es:"Isaiah Berlin, Dos conceptos de libertad.",en:"Isaiah Berlin, Two Concepts of Liberty."},{es:"Amartya Sen, Desarrollo y libertad.",en:"Amartya Sen, Development as Freedom."}] },
  { category:"investigaciones", slug:"tecnologia-y-autonomia", title:{es:"Tecnología y autonomía: un mapa del problema",en:"Technology and autonomy: mapping the problem"}, dek:{es:"Herramientas que amplían capacidades también organizan conductas.",en:"Tools that expand capacity also organize behavior."}, thesis:{es:"La autonomía tecnológica depende menos de usar o no usar una herramienta que de comprender sus incentivos, límites y poder para configurar opciones.",en:"Technological autonomy depends less on using or refusing a tool than on understanding its incentives, limits and power to configure options."}, tension:{es:"La comodidad reduce fricción; cierta fricción protege deliberación, privacidad y capacidad de aprender.",en:"Convenience reduces friction; some friction protects deliberation, privacy and the capacity to learn."}, practice:{es:"Para una herramienta habitual, enumera qué capacidad amplía, qué habilidad atrofia y qué datos necesita para funcionar.",en:"For a familiar tool, list which capacity it expands, which skill it weakens and what data it needs to work."}, references:[{es:"Martin Heidegger, La pregunta por la técnica.",en:"Martin Heidegger, The Question Concerning Technology."},{es:"Ivan Illich, La convivencialidad.",en:"Ivan Illich, Tools for Conviviality."}] },
  { category:"investigaciones", slug:"tradiciones-del-cuidado-de-si", title:{es:"Tradiciones del cuidado de sí",en:"Traditions of care of the self"}, dek:{es:"Estoicismo, prácticas espirituales y formación del carácter.",en:"Stoicism, spiritual practices and character formation."}, thesis:{es:"El cuidado de sí fue menos una obsesión privada que una disciplina para relacionarse con verdad, comunidad y acción.",en:"Care of the self was less a private obsession than a discipline for relating to truth, community and action."}, tension:{es:"La práctica personal puede cultivar libertad o privatizar problemas colectivos. Su sentido depende de cómo regresa al mundo común.",en:"Personal practice can cultivate freedom or privatize collective problems. Its meaning depends on how it returns to the common world."}, practice:{es:"Evalúa una práctica personal preguntando si aumenta tu capacidad de atención y responsabilidad hacia otros.",en:"Evaluate a personal practice by asking whether it increases your attention and responsibility toward others."}, references:[{es:"Pierre Hadot, Ejercicios espirituales y filosofía antigua.",en:"Pierre Hadot, Philosophy as a Way of Life."},{es:"Michel Foucault, La hermenéutica del sujeto.",en:"Michel Foucault, The Hermeneutics of the Subject."}] },

  { category:"perspectivas", slug:"estoicismo-control-y-cuidado", title:{es:"Estoicismo: control y cuidado",en:"Stoicism: control and care"}, dek:{es:"La dicotomía del control no es indiferencia.",en:"The dichotomy of control is not indifference."}, thesis:{es:"El estoicismo distingue lo que depende de nosotros para concentrar responsabilidad, no para retirarnos del mundo.",en:"Stoicism distinguishes what depends on us in order to concentrate responsibility, not withdraw from the world."}, tension:{es:"Mal leído, justifica pasividad; en sus fuentes, el dominio interior sostiene deberes cosmopolitas y acción justa.",en:"Misread, it justifies passivity; in its sources, inner command supports cosmopolitan duties and just action."}, practice:{es:"Separa resultado y respuesta: acepta que el primero no es tuyo por completo y concreta la segunda.",en:"Separate outcome and response: accept the first is not entirely yours and make the second concrete."} },
  { category:"perspectivas", slug:"existencialismo-libertad-situada", title:{es:"Existencialismo: libertad situada",en:"Existentialism: situated freedom"}, dek:{es:"Elegimos desde condiciones que no elegimos.",en:"We choose from conditions we did not choose."}, thesis:{es:"El existencialismo examina cómo construimos sentido sin una esencia previa que dicte quién debemos ser.",en:"Existentialism examines how we build meaning without a prior essence dictating who we must be."}, tension:{es:"Sartre radicaliza la libertad; Beauvoir muestra su situación material y su interdependencia. La agencia no es omnipotencia.",en:"Sartre radicalizes freedom; Beauvoir shows its material situation and interdependence. Agency is not omnipotence."}, practice:{es:"Describe primero tus condiciones; luego identifica el margen, aunque pequeño, cuya responsabilidad sí puedes asumir.",en:"First describe your conditions; then identify the margin, however small, whose responsibility you can assume."} },
  { category:"perspectivas", slug:"pragmatismo-ideas-y-consecuencias", title:{es:"Pragmatismo: ideas y consecuencias",en:"Pragmatism: ideas and consequences"}, dek:{es:"Una creencia también es un hábito de acción.",en:"A belief is also a habit of action."}, thesis:{es:"El pragmatismo pregunta qué diferencia concreta produce una idea en experiencia, investigación y vida común.",en:"Pragmatism asks what concrete difference an idea makes in experience, inquiry and common life."}, tension:{es:"Atender consecuencias no significa aceptar lo conveniente como verdadero; exige someter creencias a prueba pública y revisión.",en:"Attending to consequences does not make convenience true; it requires beliefs to face public testing and revision."}, practice:{es:"Ante una idea abstracta, imagina dos mundos: uno donde es verdad y otro donde no. ¿Qué conducta observable cambia?",en:"For an abstract idea, imagine two worlds: one where it is true and one where it is not. What observable conduct changes?"} },
  { category:"perspectivas", slug:"racionalismo-spinoza-y-los-afectos", title:{es:"Racionalismo: Spinoza y los afectos",en:"Rationalism: Spinoza and the affects"}, dek:{es:"Comprender una emoción cambia nuestra relación con ella.",en:"Understanding an emotion changes our relation to it."}, thesis:{es:"Para Spinoza, razón y afecto no son enemigos simples: una idea adecuada puede reorganizar potencias, vínculos y pasiones.",en:"For Spinoza, reason and affect are not simple enemies: an adequate idea can reorganize powers, relationships and passions."}, tension:{es:"Comprender causas puede liberar de culpa, pero no debe borrar responsabilidad por los efectos que producimos.",en:"Understanding causes can free us from blame, but must not erase responsibility for the effects we produce."}, practice:{es:"Describe una emoción por sus causas, cambios corporales e ideas asociadas antes de llamarla buena o mala.",en:"Describe an emotion through its causes, bodily changes and associated ideas before calling it good or bad."} },
  { category:"perspectivas", slug:"teoria-critica-y-vida-cotidiana", title:{es:"Teoría crítica y vida cotidiana",en:"Critical theory and everyday life"}, dek:{es:"Lo personal también está organizado por instituciones.",en:"The personal is also organized by institutions."}, thesis:{es:"La teoría crítica examina cómo trabajo, consumo, técnica y cultura forman necesidades que parecen espontáneamente nuestras.",en:"Critical theory examines how work, consumption, technology and culture form needs that seem spontaneously ours."}, tension:{es:"La explicación estructural revela poder, pero puede minimizar iniciativa y diferencias individuales si se vuelve total.",en:"Structural explanation reveals power, but can minimize agency and individual difference if it becomes total."}, practice:{es:"Toma un deseo cotidiano y rastrea qué industria, norma o comparación social ayuda a producirlo, sin negar tu participación.",en:"Take an everyday desire and trace which industry, norm or social comparison helps produce it, without denying your participation."} },
];

const CATEGORY_FRAMING: Record<EditorialCategoryId, LocalizedText> = {
  "preguntas-respuestas": { es:"Una respuesta filosófica no clausura la pregunta: delimita sus términos, distingue niveles y devuelve al lector una responsabilidad más precisa.", en:"A philosophical answer does not close a question: it defines its terms, distinguishes levels and returns a more precise responsibility to the reader." },
  filosofia:{es:"La filosofía trabaja haciendo explícito lo que guía una vida o una sociedad sin haber sido suficientemente examinado.",en:"Philosophy works by making explicit what guides a life or society without having been sufficiently examined."},
  conceptos:{es:"Un concepto no es una etiqueta. Es una herramienta de distinción cuyo valor depende de lo que permite ver y de lo que deja fuera.",en:"A concept is not a label. It is a tool of distinction whose value depends on what it reveals and what it leaves out."},
  claridad:{es:"La claridad no promete certeza total. Ofrece una estructura legible para separar hechos, valores, supuestos y preguntas abiertas.",en:"Clarity does not promise total certainty. It offers a legible structure for separating facts, values, assumptions and open questions."},
  podcast:{es:"Escuchar modifica el ritmo de la lectura: la voz devuelve pausas, dudas y énfasis que un resumen suele borrar.",en:"Listening changes the rhythm of reading: voice restores pauses, doubts and emphases that summaries often erase."},
  ensayos:{es:"Este ensayo propone una lectura situada, abierta a objeciones y escrita para regresar a la experiencia con mejores distinciones.",en:"This essay offers a situated reading, open to objections and written to return to experience with better distinctions."},
  investigaciones:{es:"Esta investigación organiza fuentes y perspectivas sin fingir una conclusión definitiva. Su mapa señala también límites y preguntas pendientes.",en:"This research organizes sources and perspectives without pretending to a final conclusion. Its map also marks limits and pending questions."},
  perspectivas:{es:"Una perspectiva filosófica es una lente construida desde textos y contextos históricos; ilumina una dimensión sin agotar la experiencia.",en:"A philosophical perspective is a lens built from texts and historical contexts; it illuminates one dimension without exhausting experience."},
};

export type EditorialSection = { heading: LocalizedText; paragraphs: LocalizedText[] };
export type EditorialArticle = Seed & { author: string; publishedAt: string; readingMinutes: number; sections: EditorialSection[] };

export const EDITORIAL_ARTICLES: EditorialArticle[] = S.map((seed, index) => ({
  ...seed,
  author: "Pneum",
  publishedAt: "2026-09-24",
  readingMinutes: seed.category === "investigaciones" ? 8 : seed.category === "ensayos" ? 7 : 5,
  sections: [
    { heading:{es:"Punto de partida",en:"Starting point"}, paragraphs:[seed.dek, CATEGORY_FRAMING[seed.category]] },
    { heading:{es:"La idea central",en:"The central idea"}, paragraphs:[seed.thesis, {es:"Conviene resistir la tentación de convertir esta formulación en una receta universal. Su utilidad está en permitir una observación más fina de la experiencia y en abrir razones que puedan discutirse.",en:"We should resist turning this formulation into a universal recipe. Its value lies in enabling finer observation of experience and opening reasons that can be discussed."}] },
    { heading:{es:"La tensión que no desaparece",en:"The tension that remains"}, paragraphs:[seed.tension, {es:"Pensar con claridad no elimina el conflicto. Permite reconocer qué valores compiten, qué costos implica cada vía y dónde todavía falta información.",en:"Thinking clearly does not eliminate conflict. It lets us recognize competing values, the costs of each path and where information is still missing."}] },
    { heading:{es:"Para llevarlo a tu pensamiento",en:"Bring it into your thinking"}, paragraphs:[seed.practice, {es:"No busques una conclusión automática. Escribe qué cambió en tu pregunta después de hacer esta distinción y qué merece ser examinado a continuación.",en:"Do not seek an automatic conclusion. Write what changed in your question after making this distinction and what deserves examination next."}] },
  ],
}));

export function getEditorialCategory(id: string) {
  return EDITORIAL_CATEGORIES.find((category) => category.id === id);
}

export function getEditorialArticle(category: string, slug: string) {
  return EDITORIAL_ARTICLES.find((article) => article.category === category && article.slug === slug);
}

export function editorialArticleKey(category: string, slug: string) {
  return `${category}/${slug}`;
}
