// Conocimiento Universal — red de ideas, filósofos, movimientos e ideologías.
// Dataset estático y bilingüe. Los ids son estables; `chat` enlaza con una mente viva.

import type { LocalizedString, PhilosopherId } from "./philosophers";

export type NodeKind = "philosopher" | "idea" | "movement" | "ideology" | "religion";

export type GraphNode = {
  id: string;
  label: string;
  kind: NodeKind;
  era?: string;
  note: LocalizedString;
  chat?: PhilosopherId;
};

export type LinkKind = "influence" | "opposition" | "belongs" | "develops";

export type GraphLink = {
  source: string;
  target: string;
  kind: LinkKind;
};

export const KIND_LABEL: Record<NodeKind, LocalizedString> = {
  philosopher: { es: "Filósofo", en: "Philosopher" },
  idea: { es: "Idea", en: "Idea" },
  movement: { es: "Movimiento", en: "Movement" },
  ideology: { es: "Ideología", en: "Ideology" },
  religion: { es: "Religión", en: "Religion" },
};

export const LINK_LABEL: Record<LinkKind, LocalizedString> = {
  influence: { es: "influye en", en: "influences" },
  opposition: { es: "se opone a", en: "opposes" },
  belongs: { es: "pertenece a", en: "belongs to" },
  develops: { es: "desarrolla", en: "develops" },
};

const P = (
  id: string,
  label: string,
  era: string,
  es: string,
  en: string,
  chat?: PhilosopherId,
): GraphNode => ({ id, label, kind: "philosopher", era, note: { es, en }, chat });

const N = (
  id: string,
  label: string,
  kind: NodeKind,
  es: string,
  en: string,
  era?: string,
): GraphNode => ({ id, label, kind, era, note: { es, en } });

export const GRAPH_NODES: GraphNode[] = [
  // ── Filósofos vivos en la plataforma ──────────────────────────────
  P(
    "heidegger",
    "Martin Heidegger",
    "1889–1976",
    "Pregunta por el sentido del Ser; el Dasein, la angustia y la técnica como destino.",
    "Asks the question of the meaning of Being; Dasein, anxiety, technology as destiny.",
    "heidegger",
  ),
  P(
    "schopenhauer",
    "Arthur Schopenhauer",
    "1788–1860",
    "El mundo como voluntad ciega y representación; el sufrimiento como estructura.",
    "The world as blind will and representation; suffering as structure.",
    "schopenhauer",
  ),
  P(
    "nietzsche",
    "Friedrich Nietzsche",
    "1844–1900",
    "Voluntad de poder, muerte de Dios, transvaloración de todos los valores.",
    "Will to power, death of God, revaluation of all values.",
    "nietzsche",
  ),
  P(
    "marx",
    "Karl Marx",
    "1818–1883",
    "Materialismo histórico, alienación del trabajo, crítica de la economía política.",
    "Historical materialism, alienation of labour, critique of political economy.",
    "marx",
  ),
  P(
    "james",
    "William James",
    "1842–1910",
    "Pragmatismo, corriente de conciencia, voluntad de creer.",
    "Pragmatism, stream of consciousness, the will to believe.",
    "james",
  ),
  P(
    "bentham",
    "Jeremy Bentham",
    "1748–1832",
    "Cálculo de placer y dolor: la mayor felicidad para el mayor número.",
    "Calculus of pleasure and pain: the greatest happiness for the greatest number.",
    "bentham",
  ),
  P(
    "pohlenz",
    "Max Pohlenz",
    "1872–1962",
    "Filólogo del estoicismo: la Stoa como movimiento espiritual completo.",
    "Philologist of Stoicism: the Stoa as a complete spiritual movement.",
    "pohlenz",
  ),
  P(
    "pascal",
    "Blaise Pascal",
    "1623–1662",
    "Razones del corazón, la apuesta, la miseria y grandeza del hombre.",
    "Reasons of the heart, the wager, the misery and greatness of man.",
    "pascal",
  ),
  P(
    "kierkegaard",
    "Søren Kierkegaard",
    "1813–1855",
    "El individuo ante Dios, la angustia, el salto de fe.",
    "The single individual before God, anxiety, the leap of faith.",
    "kierkegaard",
  ),
  P(
    "yannaras",
    "Christos Yannaras",
    "1935–2024",
    "Persona y comunión desde la teología ortodoxa frente al individualismo occidental.",
    "Person and communion from Orthodox theology against Western individualism.",
    "yannaras",
  ),
  P(
    "levinas",
    "Emmanuel Levinas",
    "1906–1995",
    "El rostro del Otro como origen de la ética, anterior a la ontología.",
    "The face of the Other as the origin of ethics, prior to ontology.",
    "levinas",
  ),
  P(
    "maimonides",
    "Maimónides",
    "1138–1204",
    "Guía de perplejos: teología negativa y razón aristotélica en clave judía.",
    "Guide for the Perplexed: negative theology and Aristotelian reason in Jewish key.",
    "maimonides",
  ),
  P(
    "aquinas",
    "Tomás de Aquino",
    "1225–1274",
    "Síntesis de fe y razón; ser, analogía, ley natural.",
    "Synthesis of faith and reason; being, analogy, natural law.",
    "aquinas",
  ),
  P(
    "rationalism_mind",
    "Racionalismo (Descartes · Spinoza · Leibniz)",
    "s. XVII",
    "La razón como fuente última del conocimiento cierto.",
    "Reason as the ultimate source of certain knowledge.",
    "rationalism",
  ),

  // ── Otros filósofos del ecosistema ────────────────────────────────
  P(
    "socrates",
    "Sócrates",
    "470–399 a.C.",
    "La pregunta como método; saber que no se sabe.",
    "The question as method; knowing that one does not know.",
  ),
  P(
    "plato",
    "Platón",
    "427–347 a.C.",
    "Las Ideas como realidad verdadera; el alma y la ciudad justa.",
    "Ideas as true reality; the soul and the just city.",
  ),
  P(
    "aristotle",
    "Aristóteles",
    "384–322 a.C.",
    "Sustancia, potencia y acto, virtud como término medio.",
    "Substance, potency and act, virtue as the mean.",
  ),
  P(
    "epictetus",
    "Epicteto",
    "50–135",
    "Lo que depende de nosotros y lo que no.",
    "What is up to us and what is not.",
  ),
  P(
    "augustine",
    "Agustín de Hipona",
    "354–430",
    "Interioridad, tiempo, gracia y voluntad.",
    "Interiority, time, grace and will.",
  ),
  P(
    "descartes",
    "René Descartes",
    "1596–1650",
    "Duda metódica y el cogito como primer suelo firme.",
    "Methodical doubt and the cogito as first firm ground.",
  ),
  P(
    "spinoza",
    "Baruch Spinoza",
    "1632–1677",
    "Una sola sustancia: Dios o Naturaleza.",
    "One single substance: God or Nature.",
  ),
  P(
    "leibniz",
    "G. W. Leibniz",
    "1646–1716",
    "Mónadas, razón suficiente, armonía preestablecida.",
    "Monads, sufficient reason, pre-established harmony.",
  ),
  P(
    "hume",
    "David Hume",
    "1711–1776",
    "Todo conocimiento nace de la impresión; crítica de la causalidad.",
    "All knowledge comes from impressions; critique of causality.",
  ),
  P(
    "locke",
    "John Locke",
    "1632–1704",
    "Mente como tabla rasa; propiedad y consentimiento.",
    "Mind as blank slate; property and consent.",
  ),
  P(
    "eckhart",
    "Meister Eckhart",
    "c. 1260–1328",
    "El desasimiento y el nacimiento de Dios en el fondo del alma.",
    "Detachment and the birth of God in the ground of the soul.",
    "eckhart",
  ),
  P(
    "kant",
    "Immanuel Kant",
    "1724–1804",
    "Condiciones de posibilidad de la experiencia; imperativo categórico.",
    "Conditions of possible experience; the categorical imperative.",
    "kant",
  ),
  P(
    "hegel",
    "G. W. F. Hegel",
    "1770–1831",
    "El espíritu se despliega dialécticamente en la historia.",
    "Spirit unfolds dialectically in history.",
    "hegel",
  ),
  P(
    "mill",
    "John Stuart Mill",
    "1806–1873",
    "Utilitarismo cualificado y libertad individual.",
    "Qualified utilitarianism and individual liberty.",
  ),
  P(
    "husserl",
    "Edmund Husserl",
    "1859–1938",
    "Volver a las cosas mismas: la fenomenología.",
    "Back to the things themselves: phenomenology.",
  ),
  P(
    "sartre",
    "Jean-Paul Sartre",
    "1905–1980",
    "La existencia precede a la esencia; libertad y condena.",
    "Existence precedes essence; freedom and condemnation.",
  ),
  P(
    "arendt",
    "Hannah Arendt",
    "1906–1975",
    "Acción, pluralidad, banalidad del mal.",
    "Action, plurality, the banality of evil.",
  ),
  P(
    "foucault",
    "Michel Foucault",
    "1926–1984",
    "Saber y poder: cómo se producen los sujetos.",
    "Knowledge and power: how subjects are produced.",
  ),
  P(
    "wittgenstein",
    "Ludwig Wittgenstein",
    "1889–1951",
    "Los límites de mi lenguaje son los límites de mi mundo.",
    "The limits of my language are the limits of my world.",
  ),
  P(
    "rawls",
    "John Rawls",
    "1921–2002",
    "Justicia como equidad tras el velo de ignorancia.",
    "Justice as fairness behind the veil of ignorance.",
  ),
  P(
    "smith",
    "Adam Smith",
    "1723–1790",
    "Simpatía moral y división del trabajo.",
    "Moral sympathy and division of labour.",
  ),
  P(
    "burke",
    "Edmund Burke",
    "1729–1797",
    "Prudencia, tradición y desconfianza de la abstracción revolucionaria.",
    "Prudence, tradition and distrust of revolutionary abstraction.",
  ),
  P(
    "dostoevsky",
    "F. Dostoievski",
    "1821–1881",
    "La libertad como abismo moral y religioso.",
    "Freedom as moral and religious abyss.",
  ),

  // ── Movimientos ───────────────────────────────────────────────────
  N(
    "stoicism",
    "Estoicismo",
    "movement",
    "Vivir conforme a la naturaleza y la razón; dominio de lo que depende de uno.",
    "Living according to nature and reason; mastery of what is up to us.",
    "s. III a.C.–II d.C.",
  ),
  N(
    "platonism",
    "Platonismo",
    "movement",
    "Primacía de lo inteligible sobre lo sensible.",
    "Primacy of the intelligible over the sensible.",
    "s. IV a.C.",
  ),
  N(
    "scholasticism",
    "Escolástica",
    "movement",
    "Razón y revelación articuladas en disputa ordenada.",
    "Reason and revelation articulated in ordered disputation.",
    "s. XI–XV",
  ),
  N(
    "rationalism",
    "Racionalismo",
    "movement",
    "El conocimiento cierto procede de la razón, no de los sentidos.",
    "Certain knowledge proceeds from reason, not the senses.",
    "s. XVII",
  ),
  N(
    "empiricism",
    "Empirismo",
    "movement",
    "Toda idea proviene de la experiencia sensible.",
    "Every idea derives from sense experience.",
    "s. XVII–XVIII",
  ),
  N(
    "idealism_ger",
    "Idealismo alemán",
    "movement",
    "El sujeto constituye el mundo; historia como despliegue del espíritu.",
    "The subject constitutes the world; history as unfolding of spirit.",
    "s. XVIII–XIX",
  ),
  N(
    "phenomenology",
    "Fenomenología",
    "movement",
    "Describir la experiencia tal como se da a la conciencia.",
    "Describing experience exactly as it gives itself to consciousness.",
    "s. XX",
  ),
  N(
    "existentialism",
    "Existencialismo",
    "movement",
    "El existente concreto antes que el sistema.",
    "The concrete existing individual before the system.",
    "s. XIX–XX",
  ),
  N(
    "pragmatism",
    "Pragmatismo",
    "movement",
    "El significado de una idea es su efecto práctico.",
    "The meaning of an idea is its practical effect.",
    "s. XIX–XX",
  ),
  N(
    "utilitarianism",
    "Utilitarismo",
    "movement",
    "Lo correcto es lo que maximiza el bienestar agregado.",
    "The right is what maximises aggregate welfare.",
    "s. XVIII–XIX",
  ),
  N(
    "nihilism",
    "Nihilismo",
    "movement",
    "Los valores supremos se desvalorizan.",
    "The highest values devalue themselves.",
    "s. XIX",
  ),
  N(
    "structuralism",
    "Estructuralismo / postestructuralismo",
    "movement",
    "Los sujetos son efectos de estructuras y discursos.",
    "Subjects as effects of structures and discourses.",
    "s. XX",
  ),
  N(
    "analytic",
    "Filosofía analítica",
    "movement",
    "Claridad lógica y análisis del lenguaje.",
    "Logical clarity and analysis of language.",
    "s. XX",
  ),
  N(
    "orthodox_theo",
    "Teología ortodoxa",
    "movement",
    "Persona, apófasis y comunión eclesial.",
    "Person, apophasis and ecclesial communion.",
    "s. IV–",
  ),

  // ── Ideologías políticas ──────────────────────────────────────────
  N(
    "liberalism",
    "Liberalismo",
    "ideology",
    "Libertad individual, derechos, límites al poder.",
    "Individual liberty, rights, limits on power.",
  ),
  N(
    "socialism",
    "Socialismo",
    "ideology",
    "Propiedad social de los medios de producción.",
    "Social ownership of the means of production.",
  ),
  N(
    "communism",
    "Comunismo",
    "ideology",
    "Abolición de clases y del Estado tras la revolución.",
    "Abolition of classes and the state after revolution.",
  ),
  N(
    "anarchism",
    "Anarquismo",
    "ideology",
    "Rechazo de toda autoridad coercitiva.",
    "Rejection of all coercive authority.",
  ),
  N(
    "conservatism",
    "Conservadurismo",
    "ideology",
    "Continuidad, tradición y reforma prudente.",
    "Continuity, tradition and prudent reform.",
  ),
  N(
    "social_democracy",
    "Socialdemocracia",
    "ideology",
    "Mercado corregido por redistribución y derechos sociales.",
    "Markets corrected by redistribution and social rights.",
  ),
  N(
    "republicanism",
    "Republicanismo",
    "ideology",
    "Libertad como no-dominación y virtud cívica.",
    "Freedom as non-domination and civic virtue.",
  ),
  N(
    "technocracy",
    "Tecnocracia",
    "ideology",
    "Gobierno por criterio experto y eficiencia.",
    "Rule by expert criteria and efficiency.",
  ),

  // ── Ideas / conceptos ─────────────────────────────────────────────
  N(
    "being",
    "Ser",
    "idea",
    "Aquello por lo que un ente es, y no más bien nada.",
    "That by which a being is, rather than nothing.",
  ),
  N(
    "dasein",
    "Dasein",
    "idea",
    "El ente que se pregunta por su propio ser.",
    "The being for whom its own being is a question.",
  ),
  N(
    "angst",
    "Angustia",
    "idea",
    "Apertura a la finitud y a la nada.",
    "Openness to finitude and to nothingness.",
  ),
  N(
    "technology",
    "Técnica (Gestell)",
    "idea",
    "El mundo revelado como reserva disponible.",
    "The world revealed as standing reserve.",
  ),
  N(
    "will",
    "Voluntad",
    "idea",
    "Impulso ciego que sostiene y desgarra el mundo.",
    "Blind impulse that sustains and tears the world.",
  ),
  N(
    "will_to_power",
    "Voluntad de poder",
    "idea",
    "Todo viviente busca acrecentar su potencia.",
    "Every living thing seeks to increase its power.",
  ),
  N(
    "eternal_return",
    "Eterno retorno",
    "idea",
    "Querer la propia vida infinitas veces.",
    "Willing one's own life infinitely many times.",
  ),
  N(
    "god_dead",
    "Muerte de Dios",
    "idea",
    "El fundamento suprasensible ha perdido fuerza vinculante.",
    "The suprasensible ground has lost binding force.",
  ),
  N(
    "alienation",
    "Alienación",
    "idea",
    "El trabajador se vuelve extraño a su obra y a sí mismo.",
    "The worker becomes foreign to his work and to himself.",
  ),
  N(
    "class_struggle",
    "Lucha de clases",
    "idea",
    "La historia como conflicto de intereses materiales.",
    "History as conflict of material interests.",
  ),
  N(
    "dialectic",
    "Dialéctica",
    "idea",
    "Contradicción que impulsa el movimiento del pensar y de la historia.",
    "Contradiction driving the movement of thought and history.",
  ),
  N(
    "freedom",
    "Libertad",
    "idea",
    "Capacidad de comenzar algo nuevo; también carga.",
    "Capacity to begin something new; also a burden.",
  ),
  N(
    "justice",
    "Justicia",
    "idea",
    "Reparto correcto de bienes, cargas y reconocimiento.",
    "Right distribution of goods, burdens and recognition.",
  ),
  N(
    "suffering",
    "Sufrimiento",
    "idea",
    "Experiencia límite que interroga todo sentido.",
    "Limit experience that interrogates all meaning.",
  ),
  N(
    "faith",
    "Fe",
    "idea",
    "Confianza que excede lo demostrable.",
    "Trust exceeding the demonstrable.",
  ),
  N(
    "other_face",
    "El Otro (rostro)",
    "idea",
    "Interpelación ética irreductible a concepto.",
    "Ethical summons irreducible to concept.",
  ),
  N(
    "natural_law",
    "Ley natural",
    "idea",
    "Orden moral inscrito en la naturaleza racional.",
    "Moral order inscribed in rational nature.",
  ),
  N(
    "cogito",
    "Cogito",
    "idea",
    "Pienso, luego existo: certeza inicial.",
    "I think, therefore I am: initial certainty.",
  ),
  N(
    "substance",
    "Sustancia",
    "idea",
    "Lo que existe por sí y sostiene los accidentes.",
    "What exists in itself and sustains accidents.",
  ),
  N(
    "categorical_imp",
    "Imperativo categórico",
    "idea",
    "Obra según una máxima universalizable.",
    "Act on a maxim you can universalise.",
  ),
  N(
    "social_contract",
    "Contrato social",
    "idea",
    "La autoridad legítima nace del consentimiento.",
    "Legitimate authority arises from consent.",
  ),
  N(
    "power_knowledge",
    "Poder-saber",
    "idea",
    "El saber produce y disciplina sujetos.",
    "Knowledge produces and disciplines subjects.",
  ),
  N(
    "language_limits",
    "Límites del lenguaje",
    "idea",
    "Lo que no puede decirse debe callarse.",
    "What cannot be said must be passed over in silence.",
  ),
  N(
    "greatest_happiness",
    "Mayor felicidad",
    "idea",
    "Criterio agregativo de lo correcto.",
    "Aggregative criterion of rightness.",
  ),
  N(
    "apatheia",
    "Apatheia",
    "idea",
    "Serenidad frente a lo que no depende de nosotros.",
    "Serenity before what does not depend on us.",
  ),
  N(
    "leap_faith",
    "Salto de fe",
    "idea",
    "Decisión sin garantía racional.",
    "Decision without rational guarantee.",
  ),
  N(
    "person_communion",
    "Persona y comunión",
    "idea",
    "Existir es existir en relación.",
    "To exist is to exist in relation.",
  ),
  N(
    "metaphysics_crit",
    "Crítica de la metafísica",
    "idea",
    "Las proposiciones metafísicas carecen de sentido verificable.",
    "Metaphysical propositions lack verifiable sense.",
  ),

  // ── Religiones y teologías ────────────────────────────────────────
  N(
    "judaism",
    "Judaísmo",
    "religion",
    "Alianza, Torá y la escucha de un Dios que llama por su nombre.",
    "Covenant, Torah and listening to a God who calls by name.",
  ),
  N(
    "christianity",
    "Cristianismo",
    "religion",
    "Encarnación, cruz y resurrección como centro de la historia.",
    "Incarnation, cross and resurrection as the centre of history.",
  ),
  N(
    "catholicism",
    "Catolicismo",
    "religion",
    "Tradición, sacramento y magisterio en continuidad visible.",
    "Tradition, sacrament and magisterium in visible continuity.",
  ),
  N(
    "orthodoxy",
    "Ortodoxia oriental",
    "religion",
    "Deificación (theosis), liturgia y teología apofática.",
    "Deification (theosis), liturgy and apophatic theology.",
  ),
  N(
    "protestantism",
    "Protestantismo",
    "religion",
    "Sola fide, sola scriptura, conciencia ante Dios.",
    "Sola fide, sola scriptura, conscience before God.",
  ),
  N(
    "islam",
    "Islam",
    "religion",
    "Tawhid: unicidad divina, revelación y ley.",
    "Tawhid: divine oneness, revelation and law.",
  ),
  N(
    "hinduism",
    "Hinduismo",
    "religion",
    "Atman, Brahman, karma y liberación (moksha).",
    "Atman, Brahman, karma and liberation (moksha).",
  ),
  N(
    "buddhism",
    "Budismo",
    "religion",
    "Sufrimiento, origen dependiente y extinción del apego.",
    "Suffering, dependent origination and extinction of clinging.",
  ),
  N(
    "taoism",
    "Taoísmo",
    "religion",
    "El Tao que no se nombra; actuar sin forzar (wu wei).",
    "The unnameable Tao; acting without forcing (wu wei).",
  ),
  N(
    "confucianism",
    "Confucianismo",
    "religion",
    "Ritual, piedad filial y cultivo del carácter.",
    "Ritual, filial piety and cultivation of character.",
  ),
  N(
    "kabbalah",
    "Cábala",
    "religion",
    "Sefirot, tzimtzum y la reparación del mundo.",
    "Sefirot, tzimtzum and the repair of the world.",
  ),
  N(
    "sufism",
    "Sufismo",
    "religion",
    "Vía mística del amor y la aniquilación en Dios.",
    "Mystical way of love and annihilation in God.",
  ),
  N(
    "gnosticism",
    "Gnosticismo",
    "religion",
    "Salvación por conocimiento secreto; mundo como caída.",
    "Salvation through secret knowledge; world as fall.",
  ),
  N(
    "neoplatonism_rel",
    "Neoplatonismo",
    "religion",
    "Emanación desde el Uno y retorno del alma.",
    "Emanation from the One and return of the soul.",
    "s. III–VI",
  ),
  N(
    "natural_theology",
    "Teología natural",
    "movement",
    "Camino racional hacia Dios desde el mundo.",
    "Rational path to God from the world.",
  ),
  N(
    "negative_theology",
    "Teología negativa",
    "movement",
    "De Dios sólo puede decirse lo que no es.",
    "Of God one can only say what he is not.",
  ),
  N(
    "liberation_theo",
    "Teología de la liberación",
    "movement",
    "Fe leída desde el pobre y la estructura social.",
    "Faith read from the poor and social structure.",
    "s. XX",
  ),
  N(
    "mysticism",
    "Mística",
    "movement",
    "Unión inmediata con lo divino más allá del concepto.",
    "Immediate union with the divine beyond concept.",
  ),
  N(
    "secularization",
    "Secularización",
    "idea",
    "Desplazamiento de lo sagrado del centro público.",
    "Displacement of the sacred from the public centre.",
  ),
  N(
    "theodicy",
    "Teodicea",
    "idea",
    "Justificar la bondad divina ante el mal.",
    "Justifying divine goodness in the face of evil.",
  ),
  N(
    "sacred",
    "Lo sagrado",
    "idea",
    "Lo que se sustrae y a la vez funda.",
    "That which withdraws and at once founds.",
  ),
  N(
    "transcendence",
    "Trascendencia",
    "idea",
    "Lo que excede el orden dado del mundo.",
    "What exceeds the given order of the world.",
  ),
  N(
    "theosis",
    "Theosis",
    "idea",
    "El hombre llamado a participar de lo divino.",
    "Man called to participate in the divine.",
  ),
  N(
    "revelation",
    "Revelación",
    "idea",
    "Verdad que se da y no se conquista.",
    "Truth that gives itself and is not conquered.",
  ),

  // ── Movimientos filosóficos ampliados ─────────────────────────────
  N(
    "perennialism",
    "Filosofía perenne",
    "movement",
    "Un núcleo metafísico común late en todas las tradiciones.",
    "A common metaphysical core beats in every tradition.",
  ),
  N(
    "traditionalism_sch",
    "Escuela tradicionalista",
    "movement",
    "Guénon, Coomaraswamy, Schuon: crítica del mundo moderno desde la Tradición.",
    "Guénon, Coomaraswamy, Schuon: critique of the modern world from Tradition.",
    "s. XX",
  ),
  N(
    "romanticism",
    "Romanticismo",
    "movement",
    "Genio, naturaleza, sentimiento y pueblo frente al cálculo.",
    "Genius, nature, feeling and people against calculation.",
    "s. XVIII–XIX",
  ),
  N(
    "hermeneutics",
    "Hermenéutica",
    "movement",
    "Comprender es siempre interpretar desde una tradición.",
    "To understand is always to interpret from a tradition.",
  ),
  N(
    "positivism",
    "Positivismo",
    "movement",
    "Sólo el hecho verificable cuenta como conocimiento.",
    "Only the verifiable fact counts as knowledge.",
    "s. XIX",
  ),
  N(
    "logical_positivism",
    "Positivismo lógico",
    "movement",
    "Círculo de Viena: sentido = verificabilidad.",
    "Vienna Circle: meaning = verifiability.",
    "s. XX",
  ),
  N(
    "kantianism",
    "Kantismo",
    "movement",
    "Crítica de la razón: límites y condiciones del conocer.",
    "Critique of reason: limits and conditions of knowing.",
  ),
  N(
    "neokantianism",
    "Neokantismo",
    "movement",
    "Marburgo y Baden: retorno a Kant frente al positivismo.",
    "Marburg and Baden: return to Kant against positivism.",
    "s. XIX–XX",
  ),
  N(
    "postmodernism",
    "Posmodernismo",
    "movement",
    "Incredulidad ante los grandes relatos.",
    "Incredulity towards grand narratives.",
    "s. XX",
  ),
  N(
    "deconstruction",
    "Deconstrucción",
    "movement",
    "Desmontar las oposiciones que sostienen el texto.",
    "Dismantling the oppositions that sustain the text.",
  ),
  N(
    "critical_theory",
    "Teoría crítica",
    "movement",
    "Escuela de Frankfurt: razón instrumental y dominación.",
    "Frankfurt School: instrumental reason and domination.",
    "s. XX",
  ),
  N(
    "vitalism",
    "Vitalismo",
    "movement",
    "La vida como principio irreductible al mecanismo.",
    "Life as a principle irreducible to mechanism.",
  ),
  N(
    "personalism",
    "Personalismo",
    "movement",
    "La persona como centro irreductible de valor.",
    "The person as irreducible centre of value.",
  ),
  N(
    "thomism",
    "Tomismo",
    "movement",
    "Ser, analogía y ley natural en clave aristotélica.",
    "Being, analogy and natural law in Aristotelian key.",
  ),

  // ── Espectro político: izquierda, centro, derecha ─────────────────
  N(
    "marxism_leninism",
    "Marxismo-leninismo",
    "ideology",
    "Vanguardia, partido y dictadura del proletariado.",
    "Vanguard, party and dictatorship of the proletariat.",
  ),
  N(
    "anarcho_communism",
    "Anarcocomunismo",
    "ideology",
    "Comuna libre sin Estado ni propiedad privada.",
    "Free commune without state or private property.",
  ),
  N(
    "democratic_socialism",
    "Socialismo democrático",
    "ideology",
    "Transformación social por vía electoral y sindical.",
    "Social transformation by electoral and union means.",
  ),
  N(
    "progressivism",
    "Progresismo",
    "ideology",
    "Ampliación continua de derechos e igualdad.",
    "Continuous expansion of rights and equality.",
  ),
  N(
    "green_politics",
    "Ecologismo político",
    "ideology",
    "Límite ecológico como criterio político central.",
    "Ecological limit as central political criterion.",
  ),
  N(
    "feminism",
    "Feminismo",
    "ideology",
    "Crítica de la dominación patriarcal.",
    "Critique of patriarchal domination.",
  ),
  N(
    "social_liberalism",
    "Liberalismo social",
    "ideology",
    "Libertad sostenida por condiciones materiales.",
    "Liberty sustained by material conditions.",
  ),
  N(
    "christian_democracy",
    "Democracia cristiana",
    "ideology",
    "Persona, subsidiariedad y bien común.",
    "Person, subsidiarity and the common good.",
  ),
  N(
    "centrism",
    "Centrismo",
    "ideology",
    "Moderación, pacto y rechazo del extremo.",
    "Moderation, compromise and rejection of extremes.",
  ),
  N(
    "classical_liberalism",
    "Liberalismo clásico",
    "ideology",
    "Estado mínimo, propiedad y libre intercambio.",
    "Minimal state, property and free exchange.",
  ),
  N(
    "libertarianism",
    "Libertarismo",
    "ideology",
    "Autopropiedad y no agresión como axiomas.",
    "Self-ownership and non-aggression as axioms.",
  ),
  N(
    "neoliberalism",
    "Neoliberalismo",
    "ideology",
    "Mercado como forma general de gobierno.",
    "Market as the general form of government.",
  ),
  N(
    "traditionalism_pol",
    "Tradicionalismo político",
    "ideology",
    "Orden heredado, religión y autoridad legítima.",
    "Inherited order, religion and legitimate authority.",
  ),
  N(
    "reactionary",
    "Reaccionarismo",
    "ideology",
    "Restaurar un orden anterior perdido.",
    "Restoring a lost prior order.",
  ),
  N(
    "nationalism",
    "Nacionalismo",
    "ideology",
    "La nación como sujeto político soberano.",
    "The nation as sovereign political subject.",
  ),
  N(
    "populism",
    "Populismo",
    "ideology",
    "Pueblo contra élite como eje de lo político.",
    "People against elite as the axis of politics.",
  ),
  N(
    "fascism",
    "Fascismo",
    "ideology",
    "Estado total, mito nacional y culto al líder.",
    "Total state, national myth and cult of the leader.",
  ),
  N(
    "monarchism",
    "Monarquismo",
    "ideology",
    "Legitimidad dinástica y continuidad histórica.",
    "Dynastic legitimacy and historical continuity.",
  ),
  N(
    "communitarianism",
    "Comunitarismo",
    "ideology",
    "El yo se forma en comunidades concretas.",
    "The self is formed in concrete communities.",
  ),
  N(
    "integralism",
    "Integralismo",
    "ideology",
    "Orden político ordenado al fin religioso.",
    "Political order ordered to a religious end.",
  ),
  N(
    "theocracy",
    "Teocracia",
    "ideology",
    "La ley divina como ley civil.",
    "Divine law as civil law.",
  ),
  N(
    "distributism",
    "Distributismo",
    "ideology",
    "Propiedad ampliamente repartida, escala humana.",
    "Widely distributed property, human scale.",
  ),

  // ── Derecha: pensadores ───────────────────────────────────────────
  P(
    "hobbes",
    "Thomas Hobbes",
    "1588–1679",
    "Del estado de naturaleza al Leviatán soberano.",
    "From the state of nature to the sovereign Leviathan.",
  ),
  P(
    "gramsci",
    "Antonio Gramsci",
    "1891–1937",
    "Hegemonía cultural: el poder se gana antes en la cultura.",
    "Cultural hegemony: power is won first in culture.",
  ),
  P(
    "junger",
    "Ernst Jünger",
    "1895–1998",
    "La movilización total, el Trabajador y el rebelde del bosque.",
    "Total mobilisation, the Worker and the forest rebel.",
    "junger",
  ),
  P(
    "schmitt",
    "Carl Schmitt",
    "1888–1985",
    "Lo político como distinción amigo–enemigo; la decisión soberana.",
    "The political as friend–enemy distinction; sovereign decision.",
  ),
  P(
    "spengler",
    "Oswald Spengler",
    "1880–1936",
    "Culturas como organismos: la decadencia de Occidente.",
    "Cultures as organisms: the decline of the West.",
    "spengler",
  ),
  P(
    "moeller",
    "Arthur Moeller van den Bruck",
    "1876–1925",
    "El Tercer Reino como síntesis nacional-revolucionaria.",
    "The Third Realm as national-revolutionary synthesis.",
  ),
  P(
    "niekisch",
    "Ernst Niekisch",
    "1889–1967",
    "Nacionalbolchevismo: nación y revolución contra Occidente.",
    "National bolshevism: nation and revolution against the West.",
  ),
  P(
    "sombart",
    "Werner Sombart",
    "1863–1941",
    "Héroes contra mercaderes: crítica del espíritu comercial.",
    "Heroes against merchants: critique of the commercial spirit.",
  ),
  P(
    "evola",
    "Julius Evola",
    "1898–1974",
    "Tradición primordial, jerarquía y cabalgar el tigre.",
    "Primordial tradition, hierarchy and riding the tiger.",
  ),
  P(
    "guenon",
    "René Guénon",
    "1886–1951",
    "Metafísica perenne y crítica del mundo moderno.",
    "Perennial metaphysics and critique of the modern world.",
  ),
  P(
    "maistre",
    "Joseph de Maistre",
    "1753–1821",
    "Contrarrevolución, soberanía y misterio del orden.",
    "Counter-revolution, sovereignty and the mystery of order.",
  ),
  P(
    "donoso",
    "Juan Donoso Cortés",
    "1809–1853",
    "Dictadura o disolución: teología política católica.",
    "Dictatorship or dissolution: Catholic political theology.",
  ),
  P(
    "maurras",
    "Charles Maurras",
    "1868–1952",
    "Nacionalismo integral y monarquía como orden natural.",
    "Integral nationalism and monarchy as natural order.",
  ),
  P(
    "oakeshott",
    "Michael Oakeshott",
    "1901–1990",
    "La política como conversación, no como ingeniería racional.",
    "Politics as conversation, not rational engineering.",
  ),
  P(
    "kirk",
    "Russell Kirk",
    "1918–1994",
    "La mente conservadora: orden moral y prescripción.",
    "The conservative mind: moral order and prescription.",
  ),
  P(
    "strauss",
    "Leo Strauss",
    "1899–1973",
    "Derecho natural clásico frente al historicismo moderno.",
    "Classical natural right against modern historicism.",
  ),
  P(
    "hoppe",
    "Hans-Hermann Hoppe",
    "1949–",
    "Propiedad, orden privado y crítica de la democracia.",
    "Property, private order and critique of democracy.",
  ),
  P(
    "dugin",
    "Aleksandr Duguin",
    "1962–",
    "Cuarta teoría política y geopolítica euroasiática.",
    "Fourth political theory and Eurasian geopolitics.",
  ),
  P(
    "de_benoist",
    "Alain de Benoist",
    "1943–",
    "Nueva Derecha: etnopluralismo y metapolítica gramsciana.",
    "New Right: ethnopluralism and Gramscian metapolitics.",
  ),

  // ── Derecha: corrientes e ideologías ──────────────────────────────
  N(
    "revolutionary_conservatism",
    "Revolución conservadora",
    "movement",
    "Alemania de Weimar: conservar creando, no restaurar.",
    "Weimar Germany: conserving by creating, not restoring.",
    "1918–1933",
  ),
  N(
    "national_bolshevism",
    "Nacionalbolchevismo",
    "ideology",
    "Alianza de nación y revolución contra el liberalismo.",
    "Alliance of nation and revolution against liberalism.",
  ),
  N(
    "counter_revolution",
    "Contrarrevolución",
    "movement",
    "Respuesta católica y monárquica a 1789.",
    "Catholic and monarchist reply to 1789.",
    "s. XIX",
  ),
  N(
    "integral_traditionalism",
    "Tradicionalismo integral",
    "movement",
    "Guénon y Evola: Tradición primordial contra la modernidad.",
    "Guénon and Evola: primordial Tradition against modernity.",
  ),
  N(
    "new_right",
    "Nueva Derecha",
    "movement",
    "Metapolítica, identidad y crítica del universalismo.",
    "Metapolitics, identity and critique of universalism.",
    "s. XX–XXI",
  ),
  N(
    "paleoconservatism",
    "Paleoconservadurismo",
    "ideology",
    "Nación, localismo y no intervención.",
    "Nation, localism and non-intervention.",
  ),
  N(
    "neoconservatism",
    "Neoconservadurismo",
    "ideology",
    "Virtud pública y proyección global del orden liberal.",
    "Public virtue and global projection of liberal order.",
  ),
  N(
    "national_conservatism",
    "Nacional-conservadurismo",
    "ideology",
    "Nación, familia y frontera como bienes políticos.",
    "Nation, family and border as political goods.",
  ),
  N(
    "anarcho_capitalism",
    "Anarcocapitalismo",
    "ideology",
    "Orden sin Estado por contrato y propiedad.",
    "Stateless order through contract and property.",
  ),
  N(
    "legitimism",
    "Legitimismo",
    "ideology",
    "Sólo la dinastía legítima funda el orden.",
    "Only the legitimate dynasty founds order.",
  ),
  N(
    "clerical_authoritarianism",
    "Autoritarismo clerical",
    "ideology",
    "Autoridad política sostenida por la Iglesia.",
    "Political authority sustained by the Church.",
  ),
  N(
    "identitarianism",
    "Identitarismo",
    "ideology",
    "Identidad cultural como sujeto político.",
    "Cultural identity as political subject.",
  ),
  N(
    "eurasianism",
    "Euroasianismo",
    "ideology",
    "Civilizaciones plurales frente al Occidente unipolar.",
    "Plural civilisations against the unipolar West.",
  ),
  N(
    "agrarianism",
    "Agrarismo",
    "ideology",
    "Tierra, arraigo y comunidad campesina.",
    "Land, rootedness and rural community.",
  ),

  // ── Derecha: conceptos ────────────────────────────────────────────
  N(
    "enlightenment",
    "Ilustración",
    "movement",
    "Razón, crítica y emancipación frente a la autoridad heredada.",
    "Reason, critique and emancipation against inherited authority.",
    "s. XVIII",
  ),
  N(
    "historicism",
    "Historicismo",
    "movement",
    "Todo valor es hijo de su época.",
    "Every value is a child of its epoch.",
  ),
  N(
    "capitalism",
    "Capitalismo",
    "idea",
    "Acumulación, mercado y trabajo asalariado.",
    "Accumulation, market and wage labour.",
  ),
  N(
    "democracy",
    "Democracia",
    "idea",
    "El poder legitimado por el pueblo.",
    "Power legitimised by the people.",
  ),
  N(
    "friend_enemy",
    "Amigo–enemigo",
    "idea",
    "Criterio de lo político según Schmitt.",
    "Schmitt's criterion of the political.",
  ),
  N(
    "state_of_exception",
    "Estado de excepción",
    "idea",
    "Soberano es quien decide sobre la excepción.",
    "Sovereign is who decides on the exception.",
  ),
  N(
    "political_theology",
    "Teología política",
    "idea",
    "Los conceptos del Estado son teológicos secularizados.",
    "State concepts are secularised theological ones.",
  ),
  N(
    "total_mobilization",
    "Movilización total",
    "idea",
    "La técnica convierte la vida entera en trabajo y guerra.",
    "Technique turns all life into work and war.",
  ),
  N(
    "anarch",
    "El rebelde del bosque",
    "idea",
    "Jünger: la libertad interior frente al Leviatán.",
    "Jünger: inner freedom against Leviathan.",
  ),
  N(
    "decadence",
    "Decadencia",
    "idea",
    "Las civilizaciones envejecen y se cierran.",
    "Civilisations age and close.",
  ),
  N(
    "hierarchy",
    "Jerarquía",
    "idea",
    "Orden desigual justificado por función y virtud.",
    "Unequal order justified by function and virtue.",
  ),
  N(
    "metapolitics",
    "Metapolítica",
    "idea",
    "Ganar la cultura antes que el poder.",
    "Winning culture before power.",
  ),
  N(
    "rootedness",
    "Arraigo",
    "idea",
    "Pertenencia a un lugar, linaje y costumbre.",
    "Belonging to place, lineage and custom.",
  ),
  N(
    "subsidiarity",
    "Subsidiariedad",
    "idea",
    "Decidir en la instancia más próxima posible.",
    "Deciding at the closest possible level.",
  ),
  N(
    "natural_law_right",
    "Derecho natural clásico",
    "idea",
    "Una medida del orden anterior a la ley positiva.",
    "A measure of order prior to positive law.",
  ),
  N(
    "counter_enlightenment",
    "Contrailustración",
    "idea",
    "Límite de la razón abstracta frente a historia y fe.",
    "Limit of abstract reason against history and faith.",
  ),

  // ── Conceptos político-culturales ─────────────────────────────────
  N(
    "tradition",
    "Tradición",
    "idea",
    "Transmisión viva que precede y sostiene al individuo.",
    "Living transmission preceding and sustaining the individual.",
  ),
  N(
    "nation",
    "Nación",
    "idea",
    "Comunidad de memoria, lengua y destino.",
    "Community of memory, language and destiny.",
  ),
  N(
    "sovereignty",
    "Soberanía",
    "idea",
    "Quien decide en última instancia.",
    "Who decides in the last instance.",
  ),
  N(
    "equality",
    "Igualdad",
    "idea",
    "Igual consideración y reparto de poder.",
    "Equal consideration and distribution of power.",
  ),
  N(
    "authority",
    "Autoridad",
    "idea",
    "Poder que se reconoce como legítimo.",
    "Power recognised as legitimate.",
  ),
  N(
    "modernity",
    "Modernidad",
    "idea",
    "Sujeto, progreso y desencantamiento del mundo.",
    "Subject, progress and disenchantment of the world.",
  ),
  N(
    "progress",
    "Progreso",
    "idea",
    "La historia como mejora acumulativa.",
    "History as cumulative improvement.",
  ),
  N(
    "ideology_critique",
    "Crítica de la ideología",
    "idea",
    "Las ideas encubren intereses materiales.",
    "Ideas conceal material interests.",
  ),
  N(
    "grand_narrative",
    "Gran relato",
    "idea",
    "Relato total que legitima el saber.",
    "Total narrative legitimising knowledge.",
  ),
  N(
    "difference",
    "Diferencia (différance)",
    "idea",
    "El sentido se aplaza y nunca se cierra.",
    "Meaning defers itself and never closes.",
  ),
  N(
    "interpretation",
    "Interpretación",
    "idea",
    "No hay hechos, sólo lecturas situadas.",
    "There are no facts, only situated readings.",
  ),
  N(
    "common_good",
    "Bien común",
    "idea",
    "Fin compartido que excede la suma de intereses.",
    "Shared end exceeding the sum of interests.",
  ),
];

export const GRAPH_LINKS: GraphLink[] = [
  // Antigüedad
  { source: "socrates", target: "plato", kind: "influence" },
  { source: "plato", target: "aristotle", kind: "influence" },
  { source: "plato", target: "platonism", kind: "develops" },
  { source: "platonism", target: "augustine", kind: "influence" },
  { source: "aristotle", target: "substance", kind: "develops" },
  { source: "aristotle", target: "scholasticism", kind: "influence" },
  { source: "epictetus", target: "stoicism", kind: "belongs" },
  { source: "stoicism", target: "apatheia", kind: "develops" },
  { source: "pohlenz", target: "stoicism", kind: "develops" },
  { source: "stoicism", target: "freedom", kind: "develops" },

  // Medievo
  { source: "augustine", target: "aquinas", kind: "influence" },
  { source: "aristotle", target: "aquinas", kind: "influence" },
  { source: "maimonides", target: "aquinas", kind: "influence" },
  { source: "aquinas", target: "scholasticism", kind: "belongs" },
  { source: "maimonides", target: "scholasticism", kind: "influence" },
  { source: "aquinas", target: "natural_law", kind: "develops" },
  { source: "aquinas", target: "being", kind: "develops" },
  { source: "aquinas", target: "faith", kind: "develops" },
  { source: "maimonides", target: "faith", kind: "develops" },

  // Racionalismo / empirismo
  { source: "descartes", target: "rationalism", kind: "belongs" },
  { source: "spinoza", target: "rationalism", kind: "belongs" },
  { source: "leibniz", target: "rationalism", kind: "belongs" },
  { source: "rationalism_mind", target: "rationalism", kind: "develops" },
  { source: "descartes", target: "cogito", kind: "develops" },
  { source: "spinoza", target: "substance", kind: "develops" },
  { source: "scholasticism", target: "descartes", kind: "influence" },
  { source: "locke", target: "empiricism", kind: "belongs" },
  { source: "hume", target: "empiricism", kind: "belongs" },
  { source: "empiricism", target: "rationalism", kind: "opposition" },
  { source: "locke", target: "social_contract", kind: "develops" },
  { source: "locke", target: "liberalism", kind: "influence" },
  { source: "hume", target: "kant", kind: "influence" },
  { source: "pascal", target: "faith", kind: "develops" },
  { source: "pascal", target: "rationalism", kind: "opposition" },
  { source: "descartes", target: "pascal", kind: "influence" },

  // Ilustración y idealismo
  { source: "kant", target: "categorical_imp", kind: "develops" },
  { source: "kant", target: "idealism_ger", kind: "influence" },
  { source: "hegel", target: "idealism_ger", kind: "belongs" },
  { source: "hegel", target: "dialectic", kind: "develops" },
  { source: "kant", target: "liberalism", kind: "influence" },
  { source: "smith", target: "liberalism", kind: "influence" },
  { source: "burke", target: "conservatism", kind: "develops" },
  { source: "burke", target: "liberalism", kind: "opposition" },
  { source: "bentham", target: "utilitarianism", kind: "develops" },
  { source: "bentham", target: "greatest_happiness", kind: "develops" },
  { source: "mill", target: "utilitarianism", kind: "belongs" },
  { source: "mill", target: "liberalism", kind: "influence" },
  { source: "utilitarianism", target: "categorical_imp", kind: "opposition" },
  { source: "bentham", target: "justice", kind: "develops" },

  // Marx y la política moderna
  { source: "hegel", target: "marx", kind: "influence" },
  { source: "smith", target: "marx", kind: "influence" },
  { source: "marx", target: "alienation", kind: "develops" },
  { source: "marx", target: "class_struggle", kind: "develops" },
  { source: "marx", target: "dialectic", kind: "develops" },
  { source: "marx", target: "socialism", kind: "influence" },
  { source: "marx", target: "communism", kind: "influence" },
  { source: "socialism", target: "social_democracy", kind: "influence" },
  { source: "socialism", target: "liberalism", kind: "opposition" },
  { source: "communism", target: "anarchism", kind: "opposition" },
  { source: "anarchism", target: "liberalism", kind: "influence" },
  { source: "rawls", target: "justice", kind: "develops" },
  { source: "rawls", target: "social_democracy", kind: "influence" },
  { source: "rawls", target: "liberalism", kind: "belongs" },
  { source: "rawls", target: "utilitarianism", kind: "opposition" },
  { source: "arendt", target: "republicanism", kind: "influence" },
  { source: "arendt", target: "freedom", kind: "develops" },
  { source: "technocracy", target: "republicanism", kind: "opposition" },
  { source: "technology", target: "technocracy", kind: "influence" },

  // Schopenhauer / Nietzsche
  { source: "kant", target: "schopenhauer", kind: "influence" },
  { source: "schopenhauer", target: "will", kind: "develops" },
  { source: "schopenhauer", target: "suffering", kind: "develops" },
  { source: "schopenhauer", target: "nietzsche", kind: "influence" },
  { source: "nietzsche", target: "will_to_power", kind: "develops" },
  { source: "nietzsche", target: "eternal_return", kind: "develops" },
  { source: "nietzsche", target: "god_dead", kind: "develops" },
  { source: "nietzsche", target: "nihilism", kind: "develops" },
  { source: "nietzsche", target: "platonism", kind: "opposition" },
  { source: "nietzsche", target: "utilitarianism", kind: "opposition" },
  { source: "god_dead", target: "nihilism", kind: "influence" },

  // Existencialismo / fenomenología
  { source: "kierkegaard", target: "existentialism", kind: "influence" },
  { source: "kierkegaard", target: "leap_faith", kind: "develops" },
  { source: "kierkegaard", target: "angst", kind: "develops" },
  { source: "kierkegaard", target: "hegel", kind: "opposition" },
  { source: "dostoevsky", target: "existentialism", kind: "influence" },
  { source: "dostoevsky", target: "freedom", kind: "develops" },
  { source: "husserl", target: "phenomenology", kind: "develops" },
  { source: "husserl", target: "heidegger", kind: "influence" },
  { source: "heidegger", target: "phenomenology", kind: "belongs" },
  { source: "heidegger", target: "being", kind: "develops" },
  { source: "heidegger", target: "dasein", kind: "develops" },
  { source: "heidegger", target: "angst", kind: "develops" },
  { source: "heidegger", target: "technology", kind: "develops" },
  { source: "heidegger", target: "existentialism", kind: "influence" },
  { source: "heidegger", target: "sartre", kind: "influence" },
  { source: "sartre", target: "existentialism", kind: "belongs" },
  { source: "sartre", target: "freedom", kind: "develops" },
  { source: "heidegger", target: "levinas", kind: "influence" },
  { source: "levinas", target: "other_face", kind: "develops" },
  { source: "levinas", target: "heidegger", kind: "opposition" },
  { source: "levinas", target: "phenomenology", kind: "belongs" },
  { source: "yannaras", target: "orthodox_theo", kind: "belongs" },
  { source: "yannaras", target: "person_communion", kind: "develops" },
  { source: "heidegger", target: "yannaras", kind: "influence" },
  { source: "yannaras", target: "liberalism", kind: "opposition" },
  { source: "levinas", target: "person_communion", kind: "influence" },

  // Pragmatismo, analítica, postestructuralismo
  { source: "james", target: "pragmatism", kind: "develops" },
  { source: "james", target: "faith", kind: "develops" },
  { source: "pragmatism", target: "empiricism", kind: "influence" },
  { source: "wittgenstein", target: "analytic", kind: "belongs" },
  { source: "wittgenstein", target: "language_limits", kind: "develops" },
  { source: "analytic", target: "phenomenology", kind: "opposition" },
  { source: "nietzsche", target: "foucault", kind: "influence" },
  { source: "foucault", target: "structuralism", kind: "belongs" },
  { source: "foucault", target: "power_knowledge", kind: "develops" },
  { source: "marx", target: "foucault", kind: "influence" },
  { source: "foucault", target: "liberalism", kind: "opposition" },
  { source: "arendt", target: "heidegger", kind: "opposition" },
  { source: "heidegger", target: "arendt", kind: "influence" },
  { source: "augustine", target: "kierkegaard", kind: "influence" },
  { source: "pascal", target: "kierkegaard", kind: "influence" },
  { source: "spinoza", target: "nietzsche", kind: "influence" },
  { source: "aristotle", target: "rawls", kind: "influence" },
  { source: "suffering", target: "faith", kind: "influence" },
  { source: "angst", target: "freedom", kind: "influence" },

  // ── Religiones y teologías ────────────────────────────────────────
  { source: "eckhart", target: "mysticism", kind: "belongs" },
  { source: "eckhart", target: "catholicism", kind: "belongs" },
  { source: "aquinas", target: "eckhart", kind: "influence" },
  { source: "eckhart", target: "heidegger", kind: "influence" },
  { source: "judaism", target: "christianity", kind: "influence" },
  { source: "judaism", target: "islam", kind: "influence" },
  { source: "christianity", target: "islam", kind: "influence" },
  { source: "christianity", target: "catholicism", kind: "develops" },
  { source: "christianity", target: "orthodoxy", kind: "develops" },
  { source: "christianity", target: "protestantism", kind: "develops" },
  { source: "catholicism", target: "protestantism", kind: "opposition" },
  { source: "catholicism", target: "orthodoxy", kind: "opposition" },
  { source: "orthodoxy", target: "orthodox_theo", kind: "develops" },
  { source: "orthodoxy", target: "theosis", kind: "develops" },
  { source: "orthodoxy", target: "negative_theology", kind: "influence" },
  { source: "judaism", target: "kabbalah", kind: "develops" },
  { source: "islam", target: "sufism", kind: "develops" },
  { source: "hinduism", target: "buddhism", kind: "influence" },
  { source: "buddhism", target: "suffering", kind: "develops" },
  { source: "buddhism", target: "schopenhauer", kind: "influence" },
  { source: "hinduism", target: "schopenhauer", kind: "influence" },
  { source: "taoism", target: "mysticism", kind: "influence" },
  { source: "confucianism", target: "tradition", kind: "develops" },
  { source: "neoplatonism_rel", target: "platonism", kind: "belongs" },
  { source: "neoplatonism_rel", target: "augustine", kind: "influence" },
  { source: "neoplatonism_rel", target: "negative_theology", kind: "influence" },
  { source: "neoplatonism_rel", target: "mysticism", kind: "influence" },
  { source: "gnosticism", target: "christianity", kind: "opposition" },
  { source: "kabbalah", target: "mysticism", kind: "belongs" },
  { source: "sufism", target: "mysticism", kind: "belongs" },
  { source: "mysticism", target: "negative_theology", kind: "influence" },
  { source: "maimonides", target: "judaism", kind: "belongs" },
  { source: "maimonides", target: "negative_theology", kind: "develops" },
  { source: "aquinas", target: "catholicism", kind: "belongs" },
  { source: "aquinas", target: "natural_theology", kind: "develops" },
  { source: "aquinas", target: "thomism", kind: "develops" },
  { source: "thomism", target: "scholasticism", kind: "belongs" },
  { source: "augustine", target: "christianity", kind: "belongs" },
  { source: "augustine", target: "theodicy", kind: "develops" },
  { source: "yannaras", target: "orthodoxy", kind: "belongs" },
  { source: "pascal", target: "christianity", kind: "belongs" },
  { source: "pascal", target: "natural_theology", kind: "opposition" },
  { source: "kierkegaard", target: "protestantism", kind: "belongs" },
  { source: "leibniz", target: "theodicy", kind: "develops" },
  { source: "hume", target: "natural_theology", kind: "opposition" },
  { source: "revelation", target: "faith", kind: "influence" },
  { source: "christianity", target: "revelation", kind: "develops" },
  { source: "islam", target: "revelation", kind: "develops" },
  { source: "sacred", target: "transcendence", kind: "influence" },
  { source: "secularization", target: "sacred", kind: "opposition" },
  { source: "god_dead", target: "secularization", kind: "influence" },
  { source: "modernity", target: "secularization", kind: "influence" },
  { source: "theodicy", target: "suffering", kind: "influence" },
  { source: "liberation_theo", target: "christianity", kind: "belongs" },
  { source: "marx", target: "liberation_theo", kind: "influence" },
  { source: "liberation_theo", target: "socialism", kind: "influence" },
  { source: "spinoza", target: "judaism", kind: "opposition" },
  { source: "james", target: "mysticism", kind: "influence" },

  // ── Movimientos ampliados ─────────────────────────────────────────
  { source: "perennialism", target: "traditionalism_sch", kind: "influence" },
  { source: "perennialism", target: "mysticism", kind: "influence" },
  { source: "perennialism", target: "hinduism", kind: "influence" },
  { source: "traditionalism_sch", target: "tradition", kind: "develops" },
  { source: "traditionalism_sch", target: "modernity", kind: "opposition" },
  { source: "traditionalism_sch", target: "traditionalism_pol", kind: "influence" },
  { source: "romanticism", target: "idealism_ger", kind: "influence" },
  { source: "romanticism", target: "nationalism", kind: "influence" },
  { source: "romanticism", target: "nation", kind: "influence" },
  { source: "romanticism", target: "positivism", kind: "opposition" },
  { source: "romanticism", target: "vitalism", kind: "influence" },
  { source: "romanticism", target: "existentialism", kind: "influence" },
  { source: "kant", target: "kantianism", kind: "develops" },
  { source: "kantianism", target: "neokantianism", kind: "influence" },
  { source: "neokantianism", target: "positivism", kind: "opposition" },
  { source: "neokantianism", target: "husserl", kind: "influence" },
  { source: "neokantianism", target: "hermeneutics", kind: "influence" },
  { source: "positivism", target: "logical_positivism", kind: "influence" },
  { source: "logical_positivism", target: "analytic", kind: "belongs" },
  { source: "logical_positivism", target: "metaphysics_crit", kind: "develops" },
  { source: "logical_positivism", target: "phenomenology", kind: "opposition" },
  { source: "positivism", target: "technocracy", kind: "influence" },
  { source: "hermeneutics", target: "interpretation", kind: "develops" },
  { source: "heidegger", target: "hermeneutics", kind: "influence" },
  { source: "phenomenology", target: "hermeneutics", kind: "influence" },
  { source: "nietzsche", target: "interpretation", kind: "develops" },
  { source: "nietzsche", target: "postmodernism", kind: "influence" },
  { source: "heidegger", target: "deconstruction", kind: "influence" },
  { source: "deconstruction", target: "postmodernism", kind: "belongs" },
  { source: "deconstruction", target: "difference", kind: "develops" },
  { source: "deconstruction", target: "structuralism", kind: "influence" },
  { source: "postmodernism", target: "grand_narrative", kind: "opposition" },
  { source: "postmodernism", target: "modernity", kind: "opposition" },
  { source: "postmodernism", target: "progress", kind: "opposition" },
  { source: "foucault", target: "postmodernism", kind: "belongs" },
  { source: "critical_theory", target: "marx", kind: "influence" },
  { source: "critical_theory", target: "ideology_critique", kind: "develops" },
  { source: "critical_theory", target: "technology", kind: "influence" },
  { source: "critical_theory", target: "positivism", kind: "opposition" },
  { source: "marx", target: "ideology_critique", kind: "develops" },
  { source: "vitalism", target: "nietzsche", kind: "influence" },
  { source: "personalism", target: "person_communion", kind: "develops" },
  { source: "personalism", target: "christian_democracy", kind: "influence" },
  { source: "levinas", target: "personalism", kind: "influence" },
  { source: "mysticism", target: "romanticism", kind: "influence" },

  // ── Espectro político ─────────────────────────────────────────────
  { source: "marx", target: "marxism_leninism", kind: "influence" },
  { source: "marxism_leninism", target: "communism", kind: "belongs" },
  { source: "anarchism", target: "anarcho_communism", kind: "develops" },
  { source: "anarcho_communism", target: "marxism_leninism", kind: "opposition" },
  { source: "socialism", target: "democratic_socialism", kind: "develops" },
  { source: "democratic_socialism", target: "social_democracy", kind: "influence" },
  { source: "social_democracy", target: "centrism", kind: "influence" },
  { source: "social_liberalism", target: "social_democracy", kind: "influence" },
  { source: "liberalism", target: "social_liberalism", kind: "develops" },
  { source: "liberalism", target: "classical_liberalism", kind: "develops" },
  { source: "classical_liberalism", target: "libertarianism", kind: "influence" },
  { source: "classical_liberalism", target: "neoliberalism", kind: "influence" },
  { source: "smith", target: "classical_liberalism", kind: "influence" },
  { source: "libertarianism", target: "socialism", kind: "opposition" },
  { source: "neoliberalism", target: "social_democracy", kind: "opposition" },
  { source: "neoliberalism", target: "technocracy", kind: "influence" },
  { source: "foucault", target: "neoliberalism", kind: "influence" },
  { source: "progressivism", target: "equality", kind: "develops" },
  { source: "progressivism", target: "progress", kind: "belongs" },
  { source: "progressivism", target: "conservatism", kind: "opposition" },
  { source: "feminism", target: "progressivism", kind: "belongs" },
  { source: "feminism", target: "equality", kind: "develops" },
  { source: "green_politics", target: "progressivism", kind: "influence" },
  { source: "green_politics", target: "technology", kind: "opposition" },
  { source: "christian_democracy", target: "centrism", kind: "belongs" },
  { source: "christian_democracy", target: "common_good", kind: "develops" },
  { source: "christian_democracy", target: "catholicism", kind: "influence" },
  { source: "distributism", target: "common_good", kind: "develops" },
  { source: "distributism", target: "catholicism", kind: "influence" },
  { source: "distributism", target: "neoliberalism", kind: "opposition" },
  { source: "centrism", target: "populism", kind: "opposition" },
  { source: "conservatism", target: "tradition", kind: "develops" },
  { source: "burke", target: "tradition", kind: "develops" },
  { source: "conservatism", target: "traditionalism_pol", kind: "influence" },
  { source: "traditionalism_pol", target: "monarchism", kind: "influence" },
  { source: "traditionalism_pol", target: "authority", kind: "develops" },
  { source: "traditionalism_pol", target: "integralism", kind: "influence" },
  { source: "integralism", target: "theocracy", kind: "influence" },
  { source: "integralism", target: "liberalism", kind: "opposition" },
  { source: "theocracy", target: "secularization", kind: "opposition" },
  { source: "reactionary", target: "traditionalism_pol", kind: "belongs" },
  { source: "reactionary", target: "progress", kind: "opposition" },
  { source: "nationalism", target: "nation", kind: "develops" },
  { source: "nationalism", target: "sovereignty", kind: "develops" },
  { source: "nationalism", target: "populism", kind: "influence" },
  { source: "nationalism", target: "fascism", kind: "influence" },
  { source: "fascism", target: "liberalism", kind: "opposition" },
  { source: "fascism", target: "communism", kind: "opposition" },
  { source: "fascism", target: "authority", kind: "develops" },
  { source: "populism", target: "sovereignty", kind: "develops" },
  { source: "monarchism", target: "republicanism", kind: "opposition" },
  { source: "communitarianism", target: "liberalism", kind: "opposition" },
  { source: "communitarianism", target: "common_good", kind: "develops" },
  { source: "aristotle", target: "communitarianism", kind: "influence" },
  { source: "hegel", target: "nation", kind: "influence" },
  { source: "arendt", target: "fascism", kind: "opposition" },
  { source: "rawls", target: "equality", kind: "develops" },
  { source: "yannaras", target: "orthodoxy", kind: "develops" },
  { source: "tradition", target: "authority", kind: "influence" },
  { source: "modernity", target: "progress", kind: "influence" },
  { source: "equality", target: "justice", kind: "influence" },

  // ── Derecha política: linajes, tensiones y conceptos ──────────────
  { source: "burke", target: "counter_enlightenment", kind: "develops" },
  { source: "maistre", target: "counter_revolution", kind: "develops" },
  { source: "maistre", target: "counter_enlightenment", kind: "belongs" },
  { source: "maistre", target: "enlightenment", kind: "opposition" },
  { source: "donoso", target: "counter_revolution", kind: "belongs" },
  { source: "donoso", target: "political_theology", kind: "develops" },
  { source: "donoso", target: "schmitt", kind: "influence" },
  { source: "maistre", target: "donoso", kind: "influence" },
  { source: "counter_revolution", target: "legitimism", kind: "influence" },
  { source: "legitimism", target: "monarchism", kind: "belongs" },
  { source: "maurras", target: "nationalism", kind: "develops" },
  { source: "maurras", target: "monarchism", kind: "belongs" },
  { source: "maurras", target: "clerical_authoritarianism", kind: "influence" },
  { source: "clerical_authoritarianism", target: "integralism", kind: "influence" },

  { source: "revolutionary_conservatism", target: "conservatism", kind: "influence" },
  { source: "junger", target: "revolutionary_conservatism", kind: "belongs" },
  { source: "schmitt", target: "revolutionary_conservatism", kind: "belongs" },
  { source: "spengler", target: "revolutionary_conservatism", kind: "belongs" },
  { source: "moeller", target: "revolutionary_conservatism", kind: "develops" },
  { source: "niekisch", target: "revolutionary_conservatism", kind: "belongs" },
  { source: "sombart", target: "revolutionary_conservatism", kind: "belongs" },
  { source: "junger", target: "total_mobilization", kind: "develops" },
  { source: "junger", target: "anarch", kind: "develops" },
  { source: "junger", target: "technology", kind: "influence" },
  { source: "heidegger", target: "junger", kind: "influence" },
  { source: "junger", target: "heidegger", kind: "influence" },
  { source: "nietzsche", target: "junger", kind: "influence" },
  { source: "nietzsche", target: "spengler", kind: "influence" },
  { source: "spengler", target: "decadence", kind: "develops" },
  { source: "schmitt", target: "friend_enemy", kind: "develops" },
  { source: "schmitt", target: "state_of_exception", kind: "develops" },
  { source: "schmitt", target: "political_theology", kind: "develops" },
  { source: "schmitt", target: "sovereignty", kind: "develops" },
  { source: "schmitt", target: "liberalism", kind: "opposition" },
  { source: "hobbes", target: "schmitt", kind: "influence" },
  { source: "arendt", target: "schmitt", kind: "opposition" },
  { source: "niekisch", target: "national_bolshevism", kind: "develops" },
  { source: "national_bolshevism", target: "nationalism", kind: "belongs" },
  { source: "national_bolshevism", target: "liberalism", kind: "opposition" },
  { source: "sombart", target: "capitalism", kind: "opposition" },
  { source: "revolutionary_conservatism", target: "modernity", kind: "opposition" },

  { source: "guenon", target: "integral_traditionalism", kind: "develops" },
  { source: "evola", target: "integral_traditionalism", kind: "belongs" },
  { source: "guenon", target: "evola", kind: "influence" },
  { source: "guenon", target: "perennialism", kind: "develops" },
  { source: "evola", target: "hierarchy", kind: "develops" },
  { source: "evola", target: "modernity", kind: "opposition" },
  { source: "integral_traditionalism", target: "tradition", kind: "develops" },
  { source: "integral_traditionalism", target: "progress", kind: "opposition" },
  { source: "evola", target: "new_right", kind: "influence" },
  { source: "de_benoist", target: "new_right", kind: "develops" },
  { source: "de_benoist", target: "metapolitics", kind: "develops" },
  { source: "gramsci", target: "metapolitics", kind: "influence" },
  { source: "new_right", target: "identitarianism", kind: "influence" },
  { source: "new_right", target: "neoliberalism", kind: "opposition" },
  { source: "dugin", target: "eurasianism", kind: "develops" },
  { source: "dugin", target: "integral_traditionalism", kind: "influence" },
  { source: "heidegger", target: "dugin", kind: "influence" },
  { source: "eurasianism", target: "liberalism", kind: "opposition" },
  { source: "identitarianism", target: "nation", kind: "develops" },

  { source: "conservatism", target: "national_conservatism", kind: "develops" },
  { source: "conservatism", target: "paleoconservatism", kind: "develops" },
  { source: "conservatism", target: "neoconservatism", kind: "develops" },
  { source: "national_conservatism", target: "nationalism", kind: "belongs" },
  { source: "paleoconservatism", target: "neoconservatism", kind: "opposition" },
  { source: "strauss", target: "neoconservatism", kind: "influence" },
  { source: "strauss", target: "natural_law_right", kind: "develops" },
  { source: "strauss", target: "historicism", kind: "opposition" },
  { source: "kirk", target: "conservatism", kind: "develops" },
  { source: "burke", target: "kirk", kind: "influence" },
  { source: "kirk", target: "tradition", kind: "develops" },
  { source: "oakeshott", target: "conservatism", kind: "belongs" },
  { source: "oakeshott", target: "ideology_critique", kind: "opposition" },
  { source: "oakeshott", target: "technocracy", kind: "opposition" },
  { source: "hoppe", target: "anarcho_capitalism", kind: "develops" },
  { source: "anarcho_capitalism", target: "libertarianism", kind: "belongs" },
  { source: "hoppe", target: "democracy", kind: "opposition" },
  { source: "libertarianism", target: "national_conservatism", kind: "opposition" },
  { source: "agrarianism", target: "rootedness", kind: "develops" },
  { source: "agrarianism", target: "distributism", kind: "influence" },
  { source: "christian_democracy", target: "subsidiarity", kind: "develops" },
  { source: "subsidiarity", target: "distributism", kind: "influence" },
  { source: "rootedness", target: "tradition", kind: "influence" },
  { source: "hierarchy", target: "equality", kind: "opposition" },
  { source: "natural_law_right", target: "natural_law", kind: "influence" },
  { source: "counter_enlightenment", target: "romanticism", kind: "influence" },
  { source: "traditionalism_pol", target: "integral_traditionalism", kind: "influence" },
  { source: "reactionary", target: "counter_revolution", kind: "belongs" },
  { source: "fascism", target: "revolutionary_conservatism", kind: "opposition" },
];

export const NODE_BY_ID = new Map(GRAPH_NODES.map((n) => [n.id, n]));

export function neighborsOf(id: string) {
  const out: { node: GraphNode; kind: LinkKind; direction: "out" | "in" }[] = [];
  for (const l of GRAPH_LINKS) {
    if (l.source === id) {
      const n = NODE_BY_ID.get(l.target);
      if (n) out.push({ node: n, kind: l.kind, direction: "out" });
    } else if (l.target === id) {
      const n = NODE_BY_ID.get(l.source);
      if (n) out.push({ node: n, kind: l.kind, direction: "in" });
    }
  }
  return out;
}
