import { useEffect } from "react";
import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { EditorialShell } from "@/components/editorial/editorial-shell";
import { EditorialComments } from "@/components/editorial/comment-section";
import { editorialArticleKey, getEditorialArticle, getEditorialCategory, EDITORIAL_ARTICLES } from "@/lib/editorial";
import { useI18n } from "@/lib/i18n";
import { track } from "@/lib/analytics";
import { SITE_URL } from "@/lib/site";

export const Route = createFileRoute("/editorial/$category/$article")({
  loader:({params}) => { const article=getEditorialArticle(params.category,params.article); if(!article) throw notFound(); return article; },
  component:EditorialArticlePage,
  head:({loaderData}) => { if(!loaderData) return {}; const title=`${loaderData.title.es} — Kionas.app`; const description=loaderData.dek.es; const url=`${SITE_URL}/editorial/${loaderData.category}/${loaderData.slug}`; return { meta:[{title},{name:"description",content:description},{property:"og:title",content:title},{property:"og:description",content:description},{property:"og:type",content:"article"},{property:"og:url",content:url},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:url}],scripts:[{type:"application/ld+json",children:JSON.stringify({"@context":"https://schema.org","@type":"Article",headline:loaderData.title.es,description,author:{"@type":"Organization",name:"Kionas"},publisher:{"@type":"Organization",name:"Kionas.app"},datePublished:loaderData.publishedAt,mainEntityOfPage:url})}] }; },
});
function EditorialArticlePage(){const article=Route.useLoaderData();const {lang}=useI18n();const category=getEditorialCategory(article.category);const related=EDITORIAL_ARTICLES.filter((a)=>a.category===article.category&&a.slug!==article.slug).slice(0,3);useEffect(()=>{track("editorial_article_viewed",{article:article.slug,category:article.category});},[article.slug]);return <EditorialShell><article className="mx-auto max-w-3xl px-5 py-16 md:px-8 md:py-24"><header><Link to="/editorial" search={{categoria:article.category}} className="label focus-mist text-bronze">{category?.name[lang]}</Link><h1 className="mt-5 font-serif text-display font-light leading-tight text-foreground">{article.title[lang]}</h1><p className="lead mt-6">{article.dek[lang]}</p><div className="mt-7 flex flex-wrap gap-4 border-y border-border py-4 text-micro text-muted-foreground"><span>{article.author}</span><time dateTime={article.publishedAt}>{new Intl.DateTimeFormat(lang,{dateStyle:"long"}).format(new Date(`${article.publishedAt}T12:00:00Z`))}</time><span>{article.readingMinutes} min</span></div></header><div className="mt-12 space-y-12">{article.sections.map((section)=><section key={section.heading.en}><h2 className="font-serif text-title font-light text-foreground">{section.heading[lang]}</h2><div className="mt-5 space-y-5">{section.paragraphs.map((paragraph)=><p key={paragraph.en} className="text-body leading-[1.85] text-foreground/90">{paragraph[lang]}</p>)}</div></section>)}{article.references?.length?<section><h2 className="font-serif text-title font-light text-foreground">{lang === "es" ? "Referencias para continuar" : "References for continuing"}</h2><ul className="mt-5 list-disc space-y-2 pl-5 text-small text-muted-foreground">{article.references.map((reference)=><li key={reference.en}>{reference[lang]}</li>)}</ul></section>:null}</div><aside className="mt-16 border-y border-border py-8"><p className="label">{lang === "es" ? "La pregunta sigue abierta" : "The question remains open"}</p><p className="mt-3 font-serif text-subtitle font-light text-foreground">{article.practice[lang]}</p><Link to="/oraculo" className="btn-ghost-gold focus-mist mt-6 inline-flex px-5 py-2.5 text-micro">{lang === "es" ? "Llevarlo a mi reflexión" : "Bring it into my reflection"}</Link></aside><EditorialComments articleKey={editorialArticleKey(article.category,article.slug)}/>{related.length>0&&<aside className="mt-20"><h2 className="font-serif text-title font-light text-foreground">{lang === "es" ? "Seguir leyendo" : "Keep reading"}</h2><ul className="mt-6 divide-y divide-border border-y border-border">{related.map((item)=><li key={item.slug}><Link to="/editorial/$category/$article" params={{category:item.category,article:item.slug}} className="focus-mist block py-5 font-serif text-subtitle font-light text-foreground hover:text-bronze-bright">{item.title[lang]}</Link></li>)}</ul></aside>}</article></EditorialShell>}
