/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSocratesRouteImport } from './routes/_authenticated/socrates'
import { Route as AuthenticatedReporteRouteImport } from './routes/_authenticated/reporte'
import { Route as AuthenticatedPodcastRouteImport } from './routes/_authenticated/podcast'
import { Route as AuthenticatedOraculoRouteImport } from './routes/_authenticated/oraculo'
import { Route as AuthenticatedMesaRouteImport } from './routes/_authenticated/mesa'
import { Route as AuthenticatedConocimientoRouteImport } from './routes/_authenticated/conocimiento'
import { Route as AuthenticatedBibliotecaRouteImport } from './routes/_authenticated/biblioteca'
import { Route as AuthenticatedAnalisisRouteImport } from './routes/_authenticated/analisis'
import { Route as AuthenticatedPhilosopherRouteImport } from './routes/_authenticated/$philosopher'
import { Route as ApiPodcastSpeechRouteImport } from './routes/api/podcast/speech'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSocratesRoute = AuthenticatedSocratesRouteImport.update({
  id: '/socrates',
  path: '/socrates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReporteRoute = AuthenticatedReporteRouteImport.update({
  id: '/reporte',
  path: '/reporte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPodcastRoute = AuthenticatedPodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOraculoRoute = AuthenticatedOraculoRouteImport.update({
  id: '/oraculo',
  path: '/oraculo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMesaRoute = AuthenticatedMesaRouteImport.update({
  id: '/mesa',
  path: '/mesa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConocimientoRoute =
  AuthenticatedConocimientoRouteImport.update({
    id: '/conocimiento',
    path: '/conocimiento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBibliotecaRoute = AuthenticatedBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalisisRoute = AuthenticatedAnalisisRouteImport.update({
  id: '/analisis',
  path: '/analisis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPhilosopherRoute =
  AuthenticatedPhilosopherRouteImport.update({
    id: '/$philosopher',
    path: '/$philosopher',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPodcastSpeechRoute = ApiPodcastSpeechRouteImport.update({
  id: '/api/podcast/speech',
  path: '/api/podcast/speech',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$philosopher': typeof AuthenticatedPhilosopherRoute
  '/analisis': typeof AuthenticatedAnalisisRoute
  '/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/conocimiento': typeof AuthenticatedConocimientoRoute
  '/mesa': typeof AuthenticatedMesaRoute
  '/oraculo': typeof AuthenticatedOraculoRoute
  '/podcast': typeof AuthenticatedPodcastRoute
  '/reporte': typeof AuthenticatedReporteRoute
  '/socrates': typeof AuthenticatedSocratesRoute
  '/api/podcast/speech': typeof ApiPodcastSpeechRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$philosopher': typeof AuthenticatedPhilosopherRoute
  '/analisis': typeof AuthenticatedAnalisisRoute
  '/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/conocimiento': typeof AuthenticatedConocimientoRoute
  '/mesa': typeof AuthenticatedMesaRoute
  '/oraculo': typeof AuthenticatedOraculoRoute
  '/podcast': typeof AuthenticatedPodcastRoute
  '/reporte': typeof AuthenticatedReporteRoute
  '/socrates': typeof AuthenticatedSocratesRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/podcast/speech': typeof ApiPodcastSpeechRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/$philosopher': typeof AuthenticatedPhilosopherRoute
  '/_authenticated/analisis': typeof AuthenticatedAnalisisRoute
  '/_authenticated/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/_authenticated/conocimiento': typeof AuthenticatedConocimientoRoute
  '/_authenticated/mesa': typeof AuthenticatedMesaRoute
  '/_authenticated/oraculo': typeof AuthenticatedOraculoRoute
  '/_authenticated/podcast': typeof AuthenticatedPodcastRoute
  '/_authenticated/reporte': typeof AuthenticatedReporteRoute
  '/_authenticated/socrates': typeof AuthenticatedSocratesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/podcast/speech': typeof ApiPodcastSpeechRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/sitemap.xml'
    | '/$philosopher'
    | '/analisis'
    | '/biblioteca'
    | '/conocimiento'
    | '/mesa'
    | '/oraculo'
    | '/podcast'
    | '/reporte'
    | '/socrates'
    | '/api/podcast/speech'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/privacy'
    | '/sitemap.xml'
    | '/$philosopher'
    | '/analisis'
    | '/biblioteca'
    | '/conocimiento'
    | '/mesa'
    | '/oraculo'
    | '/podcast'
    | '/reporte'
    | '/socrates'
    | '/'
    | '/api/podcast/speech'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/_authenticated'
    | '/privacy'
    | '/sitemap.xml'
    | '/_authenticated/$philosopher'
    | '/_authenticated/analisis'
    | '/_authenticated/biblioteca'
    | '/_authenticated/conocimiento'
    | '/_authenticated/mesa'
    | '/_authenticated/oraculo'
    | '/_authenticated/podcast'
    | '/_authenticated/reporte'
    | '/_authenticated/socrates'
    | '/_authenticated/'
    | '/api/podcast/speech'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPodcastSpeechRoute: typeof ApiPodcastSpeechRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/socrates': {
      id: '/_authenticated/socrates'
      path: '/socrates'
      fullPath: '/socrates'
      preLoaderRoute: typeof AuthenticatedSocratesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reporte': {
      id: '/_authenticated/reporte'
      path: '/reporte'
      fullPath: '/reporte'
      preLoaderRoute: typeof AuthenticatedReporteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/podcast': {
      id: '/_authenticated/podcast'
      path: '/podcast'
      fullPath: '/podcast'
      preLoaderRoute: typeof AuthenticatedPodcastRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oraculo': {
      id: '/_authenticated/oraculo'
      path: '/oraculo'
      fullPath: '/oraculo'
      preLoaderRoute: typeof AuthenticatedOraculoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mesa': {
      id: '/_authenticated/mesa'
      path: '/mesa'
      fullPath: '/mesa'
      preLoaderRoute: typeof AuthenticatedMesaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conocimiento': {
      id: '/_authenticated/conocimiento'
      path: '/conocimiento'
      fullPath: '/conocimiento'
      preLoaderRoute: typeof AuthenticatedConocimientoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/biblioteca': {
      id: '/_authenticated/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof AuthenticatedBibliotecaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analisis': {
      id: '/_authenticated/analisis'
      path: '/analisis'
      fullPath: '/analisis'
      preLoaderRoute: typeof AuthenticatedAnalisisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$philosopher': {
      id: '/_authenticated/$philosopher'
      path: '/$philosopher'
      fullPath: '/$philosopher'
      preLoaderRoute: typeof AuthenticatedPhilosopherRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/podcast/speech': {
      id: '/api/podcast/speech'
      path: '/api/podcast/speech'
      fullPath: '/api/podcast/speech'
      preLoaderRoute: typeof ApiPodcastSpeechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPhilosopherRoute: typeof AuthenticatedPhilosopherRoute
  AuthenticatedAnalisisRoute: typeof AuthenticatedAnalisisRoute
  AuthenticatedBibliotecaRoute: typeof AuthenticatedBibliotecaRoute
  AuthenticatedConocimientoRoute: typeof AuthenticatedConocimientoRoute
  AuthenticatedMesaRoute: typeof AuthenticatedMesaRoute
  AuthenticatedOraculoRoute: typeof AuthenticatedOraculoRoute
  AuthenticatedPodcastRoute: typeof AuthenticatedPodcastRoute
  AuthenticatedReporteRoute: typeof AuthenticatedReporteRoute
  AuthenticatedSocratesRoute: typeof AuthenticatedSocratesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPhilosopherRoute: AuthenticatedPhilosopherRoute,
  AuthenticatedAnalisisRoute: AuthenticatedAnalisisRoute,
  AuthenticatedBibliotecaRoute: AuthenticatedBibliotecaRoute,
  AuthenticatedConocimientoRoute: AuthenticatedConocimientoRoute,
  AuthenticatedMesaRoute: AuthenticatedMesaRoute,
  AuthenticatedOraculoRoute: AuthenticatedOraculoRoute,
  AuthenticatedPodcastRoute: AuthenticatedPodcastRoute,
  AuthenticatedReporteRoute: AuthenticatedReporteRoute,
  AuthenticatedSocratesRoute: AuthenticatedSocratesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPodcastSpeechRoute: ApiPodcastSpeechRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
